function getData(){
	const keysw = "www.review95.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B07D9FB15R: {href: "https://amzn.to/3my7Gs3",nameProduct: `Garmin fenix 5 plus`,image: '',summary: ``,slug: "+ amazon (CA):"},
			B07VVM1VM6: {href: "https://amzn.to/3mBCbNQ",nameProduct: `Garmin fenix 6`,image: '',summary: ``,slug: ""},
			B07SDQ2NB7: {href: "https://amzn.to/35Q2nx9",nameProduct: `BLACK+DECKER LD120VA 20-Volt Max Lithium Drill`,image: '',summary: ``,slug: ""},
			B00SOR41CO: {href: "https://amzn.to/3oFOlqK",nameProduct: `RIKON Professional Power Tools Benchtop X/Y Mortiser, 34-260`,image: '',summary: ``,slug: ""},
			B06Y2LQ5QJ: {href: "https://amzn.to/31TWiyU",nameProduct: ` Bostitch BTFP02012 6 Gallon`,image: '',summary: ``,slug: ""},
			B07HHP2JD8: {href: "https://amzn.to/3mCsTks",nameProduct: `Quipall 2-1-SIL-AL Oil Free and Silent Compressor, 1.0 HP, 2 Gallon, Aluminum Tank`,image: '',summary: ``,slug: ""},
			B07HHNSL5H: {href: "https://amzn.to/3mAKbyr",nameProduct: `Quipall 2-1-SIL Silent and Oil Free Compressor, 1.0 HP, 1.6 Gallon, Steel Tank`,image: '',summary: ``,slug: ""},
			B00IJ0ALYS: {href: "https://amzn.to/3kMvYOs",nameProduct: `DEWALT 20V MAX Cordless Drill Combo Kit, 2-Tool (DCK240C2)`,image: '',summary: ``,slug: ""},
			B0194RLK4Y: {href: "https://amzn.to/31Z10eB",nameProduct: `FLEXIMOUNTS 4x8 Overhead Garage Storage Rack…`,image: '',summary: ``,slug: ""},
			B01DLYQ4DS: {href: "https://amzn.to/37RiL3n",nameProduct: `STANLEY FATMAX PPRH7DS Professional Power Station Jump Starter: 1400 Peak/700 Instant Amps, 500W Inverter, 120 PSI Air Compressor, USB Port, Battery Clamps`,image: '',summary: ``,slug: ""},
			B078SQSNV7: {href: "https://amzn.to/3e8Hbq2",nameProduct: `Goplus Oil-Free Air Pancake Compressor Portable Quiet (3 Gallon 100 PSI 0.5HP Compressor)`,image: '',summary: ``,slug: ""},
			B004918MO2: {href: "https://amzn.to/3e9zUGx",nameProduct: `Durostar DS10000E Gas Powered 10000 Watt Electric Start Portable Generator, Red/Black`,image: '',summary: ``,slug: ""},
			B001BMDFPS: {href: "https://amzn.to/31WJ4kQ",nameProduct: `DuroMax XP4400E 4400 watt 7-Hp RV Grade Gas Generator with Electric Start`,image: '',summary: ``,slug: ""},
			B0088PTF3M: {href: "https://amzn.to/37UYPN5",nameProduct: `Durostar DS4400E Portable Generator, Red/Black`,image: '',summary: ``,slug: ""},
			B07F6PDQP6: {href: "https://amzn.to/34Lvv9T",nameProduct: `Rainier R2200i Super Quiet Portable Power Station Outdoor Inverter Generator - 1800 Running & 2200 Peak - Gas Powered - CARB Compliant`,image: '',summary: ``,slug: ""},
			B085WD92Q4: {href: "https://amzn.to/31T3I59",nameProduct: `Durostar 4,000 Watt 7HP Gas Portable Generator 50-State (4 Unit Kit)`,image: '',summary: ``,slug: ""},
			B07F88P35C: {href: "https://amzn.to/3jB6132",nameProduct: `Intex Excursion Pro Kayak, Professional Series Inflatable Fishing Kayak`,image: '',summary: ``,slug: ""},
			B07M8FFS51: {href: "https://amzn.to/32k9ZqQ",nameProduct: `Wen 11000 watt Duel Fuel Generator`,image: '',summary: ``,slug: ""},
			B07MC3TNMM: {href: "https://amzn.to/3liAIfb",nameProduct: `FunWater iSUP - Inflatable Stand Up Paddleboard `,image: '',summary: ``,slug: ""},
			B07QLVHBLF: {href: "https://amzn.to/3jHRIK2",nameProduct: `Garmin Forerunner 245 Music, GPS Running Smartwatch with Music and Advanced Dynamics, Black`,image: '',summary: ``,slug: ""},
			B07QTVMWVL: {href: "https://amzn.to/31W9BPi",nameProduct: `Garmin 010-02063-00 Forerunner 945, Premium GPS Running/Triathlon Smartwatch with Music, Black`,image: '',summary: ``,slug: ""},
			B07H4JD85M: {href: "https://amzn.to/3kCRSDL",nameProduct: `Z GRILLS ZPG-450A 2020 Upgrade Wood Pellet Grill & Smoker 6 in 1 BBQ Grill Auto Temperature Control, 450 sq in, Bronze`,image: '',summary: ``,slug: ""},
			B07YFBW4W3: {href: "https://amzn.to/3oIFQeD",nameProduct: `SUNGOLDPOWER 50A Air Plasma Cutter`,image: '',summary: ``,slug: ""},
			B076FDQC2P: {href: "https://amzn.to/34LweYF",nameProduct: `CNC Plasma Cutter, HeroCut55i Dual Voltage 120/240v`,image: '',summary: ``,slug: ""},
			B001ASTHJG: {href: "https://amzn.to/3mzFC7B",nameProduct: `Sea Eagle 370 Deluxe 3 Person Inflatable Portable Sport Kayak Canoe w/ Paddles`,image: '',summary: ``,slug: ""},
			B002R8CPRY: {href: "https://amzn.to/2TE6RkU",nameProduct: `Sunny Health & Fitness SF-E905 Elliptical Machine Cross Trainer with 8 Level Resistance and Digital Monitor`,image: '',summary: ``,slug: ""},
			B00J0S0JGS: {href: "https://amzn.to/3mBTChb",nameProduct: `Sevylor Coleman Colorado 2-Person Fishing Kayak`,image: '',summary: ``,slug: ""},
			B07HQRSQQT: {href: "https://amzn.to/3eha2IP",nameProduct: `Suunto 9, GPS Sports Watch with Long Battery Life and Wrist-Based Heart Rate`,image: '',summary: ``,slug: ""},
			B0000C16R8: {href: "https://amzn.to/3ecmlWT",nameProduct: `Fujinon Techno Stabi TS1440-14x40 Image Stabilization Binocular`,image: '',summary: ``,slug: ""},
			B07BDN8PML: {href: "https://amzn.to/2HJh3pE",nameProduct: `Champion WHEELYBIRD Electronic Trap Thrower`,image: '',summary: ``,slug: ""},
			B01MUP6L1U: {href: "https://amzn.to/3jEtkc9",nameProduct: `Westinghouse iGen2200 Portable Inverter Generator 1800 Rated & 2200 Peak Watts, Gas Powered, CARB Compliant`,image: '',summary: ``,slug: ""},
			B082P6G15G: {href: "https://amzn.to/37RkNAx",nameProduct: `Paasche Airbrush DC850R Compressor for Airbrush`,image: '',summary: ``,slug: ""},
			B078MPFN55: {href: "https://amzn.to/37Tgh4i",nameProduct: `Ring Alamr – home security system`,image: '',summary: ``,slug: ""},
			B00TL72F2E: {href: "https://amzn.to/34Gvd3S",nameProduct: `DEWALT DCBL720P1 20V MAX 5.0 Ah Lithium Ion XR Brushless Blower, Multicolor`,image: '',summary: ``,slug: ""},
			B07H4JD85M: {href: "https://amzn.to/2Gig1Re",nameProduct: `Z GRILL ZPG-700 Series Wood Pellet Grill and Smoker `,image: '',summary: ``,slug: ""},
			B00FMUYU6I: {href: "https://amzn.to/2JN6Olg",nameProduct: `Travel Berkey Gravity-Fed Water Filter with 2 Black Berkey Purification Elements`,image: '',summary: ``,slug: ""},
			B07PB4HJLZ: {href: "https://amzn.to/2HNAgqB",nameProduct: `YETI Hopper Flip Portable Cooler`,image: '',summary: ``,slug: ""},
			B0012TCFBA: {href: "https://amzn.to/2HNf7MO",nameProduct: `La Mer by LA MER La Mer Creme de La Mer--/2OZ , white`,image: '',summary: ``,slug: ""},
			B00JYUXUZO: {href: "https://amzn.to/2TAr1fN",nameProduct: `Lifetime Tamarack Angler Sit-On-Top Kayak, Olive, 120"`,image: '',summary: ``,slug: ""},
			B07NQPLB1Q: {href: "https://amzn.to/3mzJ95R",nameProduct: `Masterbuilt MB20051316 Propane Smoker with Thermostat Control, 40 inch, Black`,image: '',summary: ``,slug: ""},
			B00IVF9WL4: {href: "https://amzn.to/3oF511B",nameProduct: `Marcy Magnetic Recumbent Bike with Adjustable Resistance and Transport Wheels NS-716R`,image: '',summary: ``,slug: ""},
			B0001Q2VK0: {href: "https://amzn.to/3e7hPZK",nameProduct: `Makita MAC700 Big Bore 2.0 HP `,image: '',summary: ``,slug: ""},
			B01DOJDPQY: {href: "https://amzn.to/3ebzvmU",nameProduct: `Garmin Forerunner 735XT`,image: '',summary: ``,slug: ""},
			B07KL4QGSQ: {href: "https://amzn.to/3jI3NPx",nameProduct: `WEN 6502T 4.3-Amp 4 x 36 in. Belt and 6 in. Disc Sander with Cast Iron Base`,image: '',summary: ``,slug: ""},
			B07M8DKFML: {href: "https://amzn.to/34Iiwp2",nameProduct: `Electrolux White Front Load Laundry Pair with EFLS627UIW `,image: '',summary: ``,slug: ""},
			B07D29QNMJ: {href: "https://amzn.to/2GaAuqS",nameProduct: `Jackery Portable Power Station Explorer 240`,image: '',summary: ``,slug: ""},
			B07N5BBFZY: {href: "https://amzn.to/3kLd4aA",nameProduct: `WOPET SmartFeeder,Automatic Pet Dog and Cat Feeder`,image: '',summary: ``,slug: ""},
			B0863BNQPP: {href: "https://amzn.to/3jLCq70",nameProduct: `Honda HRX217K5VYA 187cc `,image: '',summary: ``,slug: ""},
			B081Z53L9T: {href: "https://amzn.to/2HNBB0B",nameProduct: `AstroAI Electric Cooler 26 Quarts/ 24 Liter`,image: '',summary: ``,slug: ""},
			B07YKWFDQ7: {href: "https://amzn.to/31YdBPg",nameProduct: `Husqvarna 967979301 HB32 2.5 GPM 3200 PSI `,image: '',summary: ``,slug: ""},
			B07GJBRKPC: {href: "https://amzn.to/3mBXpep",nameProduct: `Honeywell Ceiling Fans 50609-01 Xerxes Ceiling Fan, 62, Oil Rubbed Bronze`,image: '',summary: ``,slug: ""},
			B07L6Q2GSW: {href: "https://amzn.to/3jKKXXM",nameProduct: `Hunter Fan Company Hunter 59453 Transitional 44 Ceiling Fan from Minimus collection finish`,image: '',summary: ``,slug: ""},
			B01M7M9NXX: {href: "https://amzn.to/3jFrEPO",nameProduct: `Zinus Shalini Upholstered Platform Bed / Mattress Foundation / Wood Slat Support / No Box Spring Needed / Easy Assembly, Queen`,image: '',summary: ``,slug: ""},
			B07LBRDCTT: {href: "https://amzn.to/31W9jHX",nameProduct: `HONBAY Convertible Sectional Sofa Couch, L-Shaped Couch with Modern Linen Fabric for Small Space Dark Grey`,image: '',summary: ``,slug: ""},
			B07WTTCTBF: {href: "https://amzn.to/3jI4yIn",nameProduct: `Amazon Brand - 28 Palms Men's Lifeguard Sun Hat`,image: '',summary: ``,slug: ""},
			B00HVLUR54: {href: "https://amzn.to/3mzFkh0",nameProduct: `Audio-Technica ATH-M40x Professional Studio Monitor Headphone`,image: '',summary: ``,slug: ""},
			B07CYH6H4Z: {href: "https://amzn.to/3oD3g4W",nameProduct: `Amazfit Stratos Multisport Smartwatch with VO2max`,image: '',summary: ``,slug: ""},
			B07WFKN8QR: {href: "https://amzn.to/2TAbyMC",nameProduct: `Miroco Electric Kettle Temperature Control 1.7L Double Wall Keep Warm`,image: '',summary: ``,slug: ""},
			B01LWT246J: {href: "https://amzn.to/2TFfwUa",nameProduct: `Zinus Dachelle Upholstered Platform Bed Frame`,image: '',summary: ``,slug: ""},
			B07HYWDS7D: {href: "https://amzn.to/3jGXNq9",nameProduct: `Westinghouse WGen9500 Heavy Duty Portable Generator`,image: '',summary: ``,slug: ""},
			B01DVSBQZA: {href: "https://amzn.to/31T9Om3",nameProduct: `Big Ass Fans Haiku L Smart Ceiling Fan`,image: '',summary: ``,slug: ""},
			B07FPW5WXX: {href: "https://amzn.to/34Ehg6C",nameProduct: `Panda Portable Compact Top Load Washer, 1.6cu.ft, PAN56MGW2`,image: '',summary: ``,slug: ""},
			B01ISTTBY0: {href: "https://amzn.to/3kItvEM",nameProduct: `DeLonghi ECAM44660B Eletta Fully Automatic Espresso`,image: '',summary: ``,slug: ""},
			B00450U6CS: {href: "https://amzn.to/31UIELI",nameProduct: `Bissell Big Green Professional Carpet Cleaner Machine`,image: '',summary: ``,slug: ""},
			B01MRDNXPL: {href: "https://amzn.to/38m2RxW",nameProduct: `12 volt Dometic refrigerator`,image: '',summary: ``,slug: ""},
			B07S76WBGF: {href: "https://amzn.to/2HNi3ci",nameProduct: `Ninja Foodi 5-in-1 4-Qt. Air Fryer, Roast, Bake, Dehydrate Indoor Electric Grill (AG301)`,image: '',summary: ``,slug: ""},
			B083R4S47L: {href: "https://amzn.to/2HS89WL",nameProduct: `OKPRO Solar Generator Portable Power Station 540Wh`,image: '',summary: ``,slug: ""},
			B01N11EMSO: {href: "https://amzn.to/3kO9IE4",nameProduct: `Insignia- 115-Can Beverage Cooler - Stainless steel`,image: '',summary: ``,slug: ""},
			B07X551VLQ: {href: "https://amzn.to/2HHWhXr",nameProduct: `Euhomy Mini Freezer Countertop, Energy Star 1.1 Cubic Feet Single Door Compact Upright Freezer`,image: '',summary: ``,slug: ""},
			B083V8C38F: {href: "https://amzn.to/2HMw2iQ",nameProduct: `GE Smart Window Air Conditioner `,image: '',summary: ``,slug: ""},
			B07X53V3V6: {href: "https://amzn.to/3kHPMlT",nameProduct: `Eufy by Anker, BoostIQ RoboVac 30C MAX`,image: '',summary: ``,slug: ""},
			B01AL0W9YI: {href: "https://amzn.to/2TJRaZn",nameProduct: `Dr. Martens Men's 2976 Cambridge Brush Chelsea Boot Vegan`,image: '',summary: ``,slug: ""},
			B00N3CM2SK: {href: "https://amzn.to/31WLwrI",nameProduct: `Ryobi 40 Volt Chainsaw`,image: '',summary: ``,slug: ""},
			B0899FRJNL: {href: "https://amzn.to/37TWVvX",nameProduct: `Ryobi 18V ONE+ Lawn Mower Review 2020`,image: '',summary: ``,slug: ""},
			B01H21ZG30: {href: "https://amzn.to/2TEc8sI",nameProduct: `Keurig Hot 2.0 K425 Plus Series Single-serve Coffee Maker`,image: '',summary: ``,slug: ""},
			B075FGY7G2: {href: "https://amzn.to/3jKN2my",nameProduct: `Zinus Suzanne Metal and Wood Platform Bed with Headboard / Box Spring Optional / Wood Slat Support, Queen`,image: '',summary: ``,slug: ""},
			B00JXS3BXI: {href: "https://amzn.to/35Md0Bf",nameProduct: `Smittybilt GEN 2 XRC Winch`,image: '',summary: ``,slug: ""},
			B00T9RANUC: {href: "https://amzn.to/34GfIZA",nameProduct: `FLIR C2 - Compact Thermal Camera`,image: '',summary: ``,slug: ""},
			B07GYP68HW: {href: "https://amzn.to/3kLsImr",nameProduct: `Epson Home Cinema 4010 4K PRO UHD Projector`,image: '',summary: ``,slug: ""},
			B000XRQUSQ: {href: "https://amzn.to/3kMDxok",nameProduct: `Krinner Tree Genie XXL Christmas Tree Stand`,image: '',summary: ``,slug: ""},
			B00YEYKK8U: {href: "https://amzn.to/3jPYPAl",nameProduct: `OXO BREW 9 Cup Coffee Maker`,image: '',summary: ``,slug: ""},
			B01B8GQ940: {href: "https://amzn.to/2TFhvb4",nameProduct: `Zinus Mia Modern Studio 14 Inch Platform`,image: '',summary: ``,slug: ""},
			B00Q7EPPDA: {href: "https://amzn.to/3ebqlaf",nameProduct: `Zinus 12 Inch Green Tea Memory Foam Mattress `,image: '',summary: ``,slug: ""},
			B07XF9NYV3: {href: "https://amzn.to/3jKNIIC",nameProduct: `Zmodo Outdoor Wifi HD Camera System `,image: '',summary: ``,slug: ""},
			B00Q7EPPDA: {href: "https://amzn.to/2HF4JqY",nameProduct: `Zinus Memory Foam 12 Inch Mattress 2019`,image: '',summary: ``,slug: ""},
			B07VPL2HYG: {href: "https://amzn.to/3mtQcwW",nameProduct: `YnM Weighted Blanket `,image: '',summary: ``,slug: ""},
			B074MLZR3Y: {href: "https://amzn.to/3kJkiMe",nameProduct: `Brondell Swash SE400 Elongated Toilets Seat `,image: '',summary: ``,slug: ""},
			B001CNG7RY: {href: "https://amzn.to/3mCCh7G",nameProduct: `DeLonghi EC702 15-Bar-Pump Espresso Maker`,image: '',summary: ``,slug: ""},
			B003PCSR82: {href: "https://amzn.to/31UL5hk",nameProduct: `EdgeStar AP14001HS Portable Air Conditioner and Heater `,image: '',summary: ``,slug: ""},
			B074FKGR7F: {href: "https://amzn.to/34GgDt0",nameProduct: `Epson Home Cinema 2100 Projector`,image: '',summary: ``,slug: ""},
			B01MXIMVXG: {href: "https://amzn.to/3oHZZRJ",nameProduct: `ASICS Gel-Venture 6`,image: '',summary: ``,slug: ""},
			B00C1EJPJA: {href: "https://amzn.to/2TQs23z",nameProduct: `Zodiac MX8 Suction-Side Cleaner`,image: '',summary: ``,slug: ""},
			B0067MQM48: {href: "https://amzn.to/2TJSGux",nameProduct: `Zojirushi BB-PAC20BA BB-PAC20 Home Bakery Virtuoso Breadmaker `,image: '',summary: ``,slug: ""},
			B01B8DGNMQ: {href: "https://amzn.to/31WqtFw",nameProduct: `Prodigy 2.0 Leggett & Platt Adjustable Bed Base`,image: '',summary: ``,slug: ""},
			B01NAYM1TP: {href: "https://amzn.to/34F70Le",nameProduct: `LG Electronics OLED65C7P 4K Ultra HD Smart OLED TV`,image: '',summary: ``,slug: ""},
			B079V3J3Y9: {href: "https://amzn.to/3ecKOuZ",nameProduct: `LG Electronics OLED65C8P 4K Ultra HD Smart OLED TV`,image: '',summary: ``,slug: ""},
			B07B94ZR74: {href: "https://amzn.to/2TEWqNW",nameProduct: `SUPER DEAL Portable Washer Mini Washing Machine`,image: '',summary: ``,slug: ""},
			B073FMDBLJ: {href: "https://amzn.to/34I2lZ0",nameProduct: `Intex Ultraframe Pool (Rectangular Pool Set )`,image: '',summary: ``,slug: ""},
			B07ZPMCW64: {href: "https://amzn.to/3kHTzzD",nameProduct: `Ring Alamr – home security system`,image: '',summary: ``,slug: ""},
			B0722R3WV5: {href: "https://amzn.to/3oGmgzz",nameProduct: `Ring Floodlight Camera Motion-Activated HD Security Cam`,image: '',summary: ``,slug: ""},
			B07WLP395R: {href: "https://amzn.to/3eavqPM",nameProduct: `Ring Video Doorbell 3 Plus`,image: '',summary: ``,slug: ""},
			B07HXMLCBT: {href: "https://amzn.to/2GcOhxj",nameProduct: `Schlage Encode Smart WiFi Deadbolt `,image: '',summary: ``,slug: ""},
			B07S864GPW: {href: "https://amzn.to/3kUrHs8",nameProduct: `Shark IQ Robot Self Empty`,image: '',summary: ``,slug: ""},
			B07MWD9BFZ: {href: "https://amzn.to/3jI5Umb",nameProduct: `TruSens Air Purifier`,image: '',summary: ``,slug: ""},
			B07VVK39F7: {href: "https://amzn.to/37SeFIc",nameProduct: ` H13 True HEPA Air Purifiers Filter`,image: '',summary: ``,slug: ""},
			B07T8YV9WS: {href: "https://amzn.to/2U5Zxi9",nameProduct: `SUNGZU 1000 Watt Portable Power Station `,image: '',summary: ``,slug: ""},
			B00154MGXY: {href: "https://amzn.to/2JIkEoR",nameProduct: `Sauder Storage Cabinet `,image: '',summary: ``,slug: ""},
			B0888Y891H: {href: "https://amzn.to/32pqJNt",nameProduct: `Nectar Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B07RSZSYNC: {href: "https://amzn.to/3p6fByN",nameProduct: `Levoit Core 300 Portable Air Purifier `,image: '',summary: ``,slug: ""},
			B07DVRK8LW: {href: "https://amzn.to/3oXiYrZ",nameProduct: `Brand Classic Mercer Pillow Top Cool Gel Memory Foam and Innerspring Hybrid 12 inch Mattress`,image: '',summary: ``,slug: ""},
			B00Q7EPSHI: {href: "https://amzn.to/35AxPkl",nameProduct: `Zinus 12 Inch Green Tea Memory Foam Mattress `,image: '',summary: ``,slug: ""},
			B07GPNZSMY: {href: "https://amzn.to/2IT1QTi",nameProduct: `SNAPTAIN S5C WiFi FPV Drone `,image: '',summary: ``,slug: ""},
			B01IU6RP12: {href: "https://amzn.to/3fbiw4B",nameProduct: `Linenspa 8 Inch Memory Foam and Innerspring Hybrid Mattress`,image: '',summary: ``,slug: ""},
			B078WKT1HL: {href: "https://amzn.to/3kHmSla",nameProduct: `Holy Stone HS110D FPV RC Drone`,image: '',summary: ``,slug: ""},
			B0798FVV6V: {href: "https://amzn.to/35ErFzz",nameProduct: `Dyson Cyclone V10 Absolute Lightweight Cordless Stick Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B0784ZKVKF: {href: "https://amzn.to/3pIlSkr",nameProduct: `Camp Chef SmokePro DLX Pellet Grill`,image: '',summary: ``,slug: ""},
			B00QBZ25R4: {href: "https://amzn.to/2JcoHK1",nameProduct: `TUFT & NEEDLE foam mattress`,image: '',summary: ``,slug: ""},
			B01BMCWJ7G: {href: "https://amzn.to/2KEZTLo",nameProduct: ` BedJet V2`,image: '',summary: ``,slug: ""},
			B07XSCBSN5: {href: "https://amzn.to/3pZOm9B",nameProduct: `Amazon Smart Oven`,image: '',summary: ``,slug: ""},
			B07FK86JQ9: {href: "https://amzn.to/3maLLHE",nameProduct: `Hydra 8-Blade Smart Ceiling Fan 120in Bronze `,image: '',summary: ``,slug: ""},
			B08FXT36RD: {href: "https://amzn.to/39ZCjn5",nameProduct: `2017 Diamondback Atroz Comp `,image: '',summary: ``,slug: ""},
			B08FXT36RD: {href: "https://amzn.to/39ZCjn5",nameProduct: `Diamondback 2017 Mission Pro Mountain Bike Red `,image: '',summary: ``,slug: ""},
			B08FXT36RD: {href: "https://amzn.to/39ZCjn5",nameProduct: `Diamondback 2017 Recoil 29er`,image: '',summary: ``,slug: ""},
			B08FXT36RD: {href: "https://amzn.to/39ZCjn5",nameProduct: `Diamondback Mission 1(2017)`,image: '',summary: ``,slug: ""},
			B08G4FWXJK: {href: "https://amzn.to/3nf8T8k",nameProduct: `Review Diamondback Catch 1`,image: '',summary: ``,slug: ""},
			B08FXT36RD: {href: "https://amzn.to/39ZCjn5",nameProduct: `Review DiamondBack Release 2 29er`,image: '',summary: ``,slug: ""},
			B08FXT36RD: {href: "https://amzn.to/39ZCjn5",nameProduct: `Diamondback version 1(2019) Review`,image: '',summary: ``,slug: ""},
			B08FXT36RD: {href: "https://amzn.to/39ZCjn5",nameProduct: `Diamondback Release 2 review 2020`,image: '',summary: ``,slug: ""},
			B08FXT36RD: {href: "https://amzn.to/39ZCjn5",nameProduct: `Ellsworth Enlightenment 29 Mountain Bike`,image: '',summary: ``,slug: ""},
			B08FXT36RD: {href: "https://amzn.to/39ZCjn5",nameProduct: `Diamondback Release 2 review`,image: '',summary: ``,slug: ""},
			B0863TXGM3: {href: "https://amzn.to/3gTcWEP",nameProduct: `Sony WH-1000XM4`,image: '',summary: ``,slug: ""},
			B07H2HQJR5: {href: "https://amzn.to/3nJc608",nameProduct: `Open the box and review Callaway Strata 2020`,image: '',summary: ``,slug: ""},
			B07M7LC38W: {href: "https://amzn.to/3aAMcb9",nameProduct: `TaylorMade M6 Driver`,image: '',summary: ``,slug: ""},
			B07VWXW2NV: {href: "https://amzn.to/3nI7Lu0",nameProduct: `TaylorMade P790 Irons`,image: '',summary: ``,slug: ""},
			B07H2CKPJV: {href: "https://amzn.to/3nEjIBd",nameProduct: `Review Callaway Edge Golf Set 2020`,image: '',summary: ``,slug: ""},
			B0013LLSZG: {href: "https://amzn.to/2KzKITT",nameProduct: `Camp Chef Outdoor Camp Oven`,image: '',summary: ``,slug: ""},
			B004K0Q8LG: {href: "https://amzn.to/34DLYfH",nameProduct: `Evaluation and assembly of LifeTime Climbing Dome 2020`,image: '',summary: ``,slug: ""},
			B004K0Q8LG: {href: "https://amzn.to/37JSxPE",nameProduct: `Lifetime Geometric Dome Climber Play Center review 2020`,image: '',summary: ``,slug: ""},
			B0013LLSZG: {href: "https://amzn.to/2KSLJX0",nameProduct: `Campervan oven review 2020`,image: '',summary: ``,slug: ""},
			B07BHJ6GW2: {href: "https://amzn.to/2WMiaZY",nameProduct: `KODAK PIXPRO AZ528 review 2020`,image: '',summary: ``,slug: ""},
			B074WK5GW9: {href: "https://amzn.to/3o3Yz3D",nameProduct: `Kodak PIXPRO AZ401 Review 2020`,image: '',summary: ``,slug: ""},
			B00TOZLAV0: {href: "https://amzn.to/3ppDvoq",nameProduct: `Oster 6-Slice Convection Countertop Oven `,image: '',summary: ``,slug: ""},
			B0721ZMW8K: {href: "https://amzn.to/3rKA4e0",nameProduct: `Review cookoo rice cooker DHSR0609F`,image: '',summary: ``,slug: ""},
			B0752VWV65: {href: "https://amzn.to/38aCJ8M",nameProduct: `Hamilton Beach Rice Cooker`,image: '',summary: ``,slug: ""},
			B015PDVY6K: {href: "https://amzn.to/3rR6iEg",nameProduct: `Midea 1.8L Multi Cooker`,image: '',summary: ``,slug: ""},
			B07CHZP91L: {href: "https://amzn.to/2X8U0Jl",nameProduct: `Dash DRCM200BK Mini Rice Cooker `,image: '',summary: ``,slug: ""},
			B007JNNN5U: {href: "https://amzn.to/38akVuu",nameProduct: `Oster 6-Cup Rice Cooker `,image: '',summary: ``,slug: ""},
			B008C9UCH2: {href: "https://amzn.to/3ohtlWw",nameProduct: `Panasonic 5 Cup/SR-DF101 `,image: '',summary: ``,slug: ""},
			B000A7NN4I: {href: "https://amzn.to/3rVZJ3h",nameProduct: `Zojirushi NS-ZCC18 10 cup rice cooker `,image: '',summary: ``,slug: ""},
			B003O7OW2I: {href: "https://amzn.to/396VzwO",nameProduct: `Tatung TAC-11KN Multi-Purpose Kitchen `,image: '',summary: ``,slug: ""},
			B00EZZ5KBU: {href: "https://amzn.to/35tl4rt",nameProduct: `Cuckoo CRP-HZ0683FR`,image: '',summary: ``,slug: ""},
			B00007J5U7: {href: "https://amzn.to/3ba75tX",nameProduct: `Zojirushi Neuro Fuzzy NS-SCC10`,image: '',summary: ``,slug: ""},
			B001KBY9M8: {href: "https://amzn.to/3bmGLwV",nameProduct: `Oster Rice Cooker Review 2021`,image: '',summary: ``,slug: ""},
			B07NPHC5NH: {href: "https://amzn.to/3boQpPE",nameProduct: `TOBBI Kids 12V Review 2021`,image: '',summary: ``,slug: ""},
			B07NPHC5NH: {href: "https://amzn.to/3boQpPE",nameProduct: `12V-TOBBI Kids battery powered truck review`,image: '',summary: ``,slug: ""},
			B07PCPWYF1: {href: "https://amzn.to/3hYHiGt",nameProduct: `12 Volt Explorer Truck Battery Powered`,image: '',summary: ``,slug: ""},
			B08222H88W: {href: "https://amzn.to/3hXTxDi",nameProduct: `TOBBI Kids Ride On Car Maserati 12V`,image: '',summary: ``,slug: ""},
			B08222H88W: {href: "https://amzn.to/3hXTxDi",nameProduct: `Handling and assembling children's cars MASERATI 12V`,image: '',summary: ``,slug: ""},
			B08222H88W: {href: "https://amzn.to/3hXTxDi",nameProduct: `TOBBI Kids Ride On Car Maserati 12V`,image: '',summary: ``,slug: ""},
			B07N6683CP: {href: "https://amzn.to/3q8kNBP",nameProduct: `Review children's car TOBBI- Mercedes Benz 12V`,image: '',summary: ``,slug: ""},
			B07N6683CP: {href: "https://amzn.to/3q8kNBP",nameProduct: `TOBBI Licensed Mercedes Benz 12V Kids Ride On Car `,image: '',summary: ``,slug: ""},
			B07N6683CP: {href: "https://amzn.to/3q8kNBP",nameProduct: `TOBBI Licensed Mercedes Benz 12V Kids Ride On Car `,image: '',summary: ``,slug: ""},
			B07Z4ZK3TQ: {href: "https://amzn.to/39f0YSw",nameProduct: `Uenjoy 12V Licensed Mercedes-Benz G63 Kids Ride`,image: '',summary: ``,slug: ""},
			B0848R3R83: {href: "https://amzn.to/39sqofU",nameProduct: `Mercedes Benz AMG GTR battery-powered children's car assembly`,image: '',summary: ``,slug: ""},
			B07YW91K4X: {href: "https://amzn.to/3bAbgQh",nameProduct: `Lamborghini Aventador SVJ car is powered by a 12v battery`,image: '',summary: ``,slug: ""},
			B07YW91K4X: {href: "https://amzn.to/3bAbgQh",nameProduct: `Lamborghini Aventador SVJ car driver for kids`,image: '',summary: ``,slug: ""},
			B07JFGJZXK: {href: "https://amzn.to/3i18Fjt",nameProduct: `Lamborghini Aventador SV Sports Car Toy Review 2021`,image: '',summary: ``,slug: ""},
			B07JFGJZXK: {href: "https://amzn.to/3i18Fjt",nameProduct: `Lamborghini Aventador SV Kids Sports Car review `,image: '',summary: ``,slug: ""},
			B07YW91K4X: {href: "https://amzn.to/3bAbgQh",nameProduct: `Car-driven Lamborghini Aventador for young children`,image: '',summary: ``,slug: ""},
			B08L9R6S7W: {href: "https://amzn.to/35SmAmW",nameProduct: `Aosom 12V UTV Truck Toy Review`,image: '',summary: ``,slug: ""},
			B08L9R6S7W: {href: "https://amzn.to/35SmAmW",nameProduct: `UTV Truck Toy Review`,image: '',summary: ``,slug: ""},
			B06WWDKZSC: {href: "https://amzn.to/3atVfJk",nameProduct: `BRIS 12ft Inflatable Boats Review`,image: '',summary: ``,slug: ""},
			B08GK8LSQS: {href: "https://amzn.to/3cDkrji",nameProduct: `ClicBot Coding Robot Kit for Kids - Review 2021`,image: '',summary: ``,slug: ""},
			B07V7Z3LDG: {href: "https://amzn.to/36IaVrl",nameProduct: `Champion 3800-Watt Dual Fuel RV Ready Portable Generator review 2021`,image: '',summary: ``,slug: ""},
			B07YNHZMYF: {href: "https://amzn.to/39NOKC8",nameProduct: `Pelicans intruder 12 Review 2021`,image: '',summary: ``,slug: ""},
			B08GK8LSQS: {href: "https://amzn.to/3joTSzz",nameProduct: `ClicBot Coding Robot Kits review 2021`,image: '',summary: ``,slug: ""},
			B07G3ZNK4Y: {href: "https://amzn.to/3pVOiXP",nameProduct: `Vector Robot review 2021`,image: '',summary: ``,slug: ""},
			B07G3ZNK4Y: {href: "https://amzn.to/3pVOiXP",nameProduct: `Open the box and evaluate the robot vecter 2021`,image: '',summary: ``,slug: ""},
			B07NX34P7F: {href: "https://amzn.to/3wvJuMH",nameProduct: `Fanaway 21093001 Evo2`,image: '',summary: ``,slug: ""},
			B084GZJL47: {href: "https://amzn.to/3wzwzJx",nameProduct: `Minka-Aire F896-84-BNW`,image: '',summary: ``,slug: ""},
			B07NX55VWR: {href: "https://amzn.to/2PXvnPq",nameProduct: `Fanaway 21103501 Evo1 `,image: '',summary: ``,slug: ""},
			B07STXCNXW: {href: "https://amzn.to/3dCAVHf",nameProduct: `Calphalon BVCLECMP1 Temp iQ Espresso Machine`,image: '',summary: ``,slug: ""},
			B00CLD39C0: {href: "https://amzn.to/3us1jdH",nameProduct: `Rowenta DW9280 Digital Display Steam Iron`,image: '',summary: ``,slug: ""},
			B073WJL99W: {href: "https://amzn.to/39MYCvs",nameProduct: `Blueair Blue Pure 211+ Air Purifier `,image: '',summary: ``,slug: ""},
			B07J6GCMX3: {href: "https://amzn.to/3cRtmx6",nameProduct: `Alen BreatheSmart air purifier`,image: '',summary: ``,slug: ""},
			B07R64K7QV: {href: "https://amzn.to/3sYu1T9",nameProduct: `Decorelex 30 Inch Electric Stove Induction Cooktop`,image: '',summary: ``,slug: ""},
			B07D78Y5TN: {href: "https://amzn.to/3fMggmU",nameProduct: `BoostIQ RoboVac 11S (Slim), Robot vacuum cleaner, `,image: '',summary: ``,slug: ""},
			B078MGY2CS: {href: "https://amzn.to/39M3PDO",nameProduct: `Giantex Full Automatic Washing Machine 1,34 Cu ft `,image: '',summary: ``,slug: ""},
			B07VR22832: {href: "https://amzn.to/3cQV9ho",nameProduct: `Farberware FDW05ASBWHA Complete Portable`,image: '',summary: ``,slug: ""},
			B00IR8H55A: {href: "https://amzn.to/3rVwQ5Y",nameProduct: `RCA RFR322-B 3.2 Cu Ft Single Door Mini Fridge`,image: '',summary: ``,slug: ""},
			B072N3T79P: {href: "https://amzn.to/3rTMiQf",nameProduct: `Panasonic Link2Cell Bluetooth Cordless Phone`,image: '',summary: ``,slug: ""},
			B00IJJQ57Q: {href: "https://amzn.to/31WThNz",nameProduct: `Adesso Trinity 3 Arc Floor Lamp`,image: '',summary: ``,slug: ""},
			B07Y1HK5BW: {href: "https://amzn.to/3mq74Gc",nameProduct: `GILOBABY Robot Toys`,image: '',summary: ``,slug: ""},
			B07Q33HD6X: {href: "https://amzn.to/3uxyFIl",nameProduct: `IKICH Portable Ice Maker Machine for Countertop`,image: '',summary: ``,slug: ""},
			B00BD9OKC6: {href: "https://amzn.to/3sPsmPL",nameProduct: `Streamlight 75458 Stinger DS LED Flashlight`,image: '',summary: ``,slug: ""},
			B0148O658Y: {href: "https://amzn.to/2OtRooK",nameProduct: `Bosch Electric Mini-Tank Water Heater Tronic 3000 T 2.5`,image: '',summary: ``,slug: ""},
			B00NO56WF0: {href: "https://amzn.to/3dHCh3q",nameProduct: `InSinkErator HWT-00 Hot Water Heater`,image: '',summary: ``,slug: ""},
			B089KVB43X: {href: "https://amzn.to/3rX9sFg",nameProduct: `SEAFLO 33-Series industrial water pressure pump `,image: '',summary: ``,slug: ""},
			B0786TJC33: {href: "https://amzn.to/2PV0fA5",nameProduct: `hOmeLabs Beverage Refrigerator and Cooler`,image: '',summary: ``,slug: ""},
			B01JRTZVVM: {href: "https://amzn.to/3rUJnqy",nameProduct: `Cuckoo pressure rice cooker`,image: '',summary: ``,slug: ""},
			B07DP911QL: {href: "https://amzn.to/31RDeAU",nameProduct: `Fellow Stagg EKG + Electric kettle`,image: '',summary: ``,slug: ""},
			B01N5SBKLW: {href: "https://amzn.to/31PAELF",nameProduct: `Makita XFD12T 5.0 Ah `,image: '',summary: ``,slug: ""},
			B00IUKKMDC: {href: "https://amzn.to/3wuD4xp",nameProduct: `WEN 56475 4750-Watt Portable Generator`,image: '',summary: ``,slug: ""},
			B07VWMCWYX: {href: "https://amzn.to/3sVmGDW",nameProduct: `Dell Optiplex 7010 PC`,image: '',summary: ``,slug: ""},
			B089YSKJY6: {href: "https://amzn.to/2RdAQCn",nameProduct: `COMFEE’ 1.6 Cu.ft Portable Washing Machine`,image: '',summary: ``,slug: ""},
			B08P4PG4Y7: {href: "https://amzn.to/39M15WN",nameProduct: `Laptop Lenovo Ideapad 3 15`,image: '',summary: ``,slug: ""},
			B08C9PXPMM: {href: "https://amzn.to/39OuY91",nameProduct: `SILJOY Reversible Industrial Ceiling Fan`,image: '',summary: ``,slug: ""},
			B08NLPX4CW: {href: "https://amzn.to/3uxBf0Z",nameProduct: `JBL Xtreme 3 - Portable Bluetooth Speaker`,image: '',summary: ``,slug: ""},
			B07HPS9XJR: {href: "https://amzn.to/31SUHJ0",nameProduct: `Marshall Stanmore II Wireless Bluetooth Speaker`,image: '',summary: ``,slug: ""},
			B07FD5FZ9P: {href: "https://amzn.to/3wylN6w",nameProduct: `Bose Home Speaker 500`,image: '',summary: ``,slug: ""},
			B07RMZV7W4: {href: "https://amzn.to/2PDCgWm",nameProduct: `SereneLife SLPAC Portable Air Conditioner`,image: '',summary: ``,slug: ""},
			B079397NXJ: {href: "https://amzn.to/31PXC5j",nameProduct: `Smeg KFL04 PGUS kettle`,image: '',summary: ``,slug: ""},
			B08L9NRL1Y: {href: "https://amzn.to/3s2X0Eh",nameProduct: `McLaren 720S Memphis Red Metallic 1/18 `,image: '',summary: ``,slug: ""},
			B00CYW3EVO: {href: "https://amzn.to/3mmLK46",nameProduct: `Big Berkey Gravity-Fed Water Filter `,image: '',summary: ``,slug: ""},
			B07VWCY2JF: {href: "https://amzn.to/39IXR6n",nameProduct: `Energy Star dishwasher`,image: '',summary: ``,slug: ""},
			B00CMBJ1VE : {href: "https://amzn.to/3cQY4qj",nameProduct: `Intex Excursion Inflatable Boat Series`,image: '',summary: ``,slug: ""},
			B01MV2225G: {href: "https://amzn.to/3fTeUXg",nameProduct: `Classic accessories T-Top Central Control Panel`,image: '',summary: ``,slug: ""},
			B07RQC1GHZ: {href: "https://amzn.to/3sQuiHI",nameProduct: `Coredy R750 Robot Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07V1JW4GF: {href: "https://amzn.to/3ustoSg",nameProduct: `BISSELL Iconpet wireless`,image: '',summary: ``,slug: ""},
			B01N3A9N2H: {href: "https://amzn.to/3upKekt",nameProduct: `Dyson AM09 heating fan`,image: '',summary: ``,slug: ""},
			B08CPHFD9J: {href: "https://amzn.to/2Rarpng",nameProduct: `Air Purifiers Allel BreatheSmart Flex`,image: '',summary: ``,slug: ""},
			B019XIZ5I6: {href: "https://amzn.to/3wxborB",nameProduct: `Lifetime Kodiak Canoe`,image: '',summary: ``,slug: ""},
			B08GHVSGMQ: {href: "https://amzn.to/3sU1ka5",nameProduct: `Samsung Galaxy Tab A7`,image: '',summary: ``,slug: ""},
			B08J65DST5: {href: "https://amzn.to/3mnKnlK",nameProduct: `New Apple iPad`,image: '',summary: ``,slug: ""},
			B084JBTYHJ: {href: "https://amzn.to/2OpR621",nameProduct: `SAMSUNG 65-inch Class Crystal Smart TV`,image: '',summary: ``,slug: ""},
			B01DEWZWDU: {href: "https://amzn.to/3fMPdbc",nameProduct: `Panasonic Microwave Oven NN`,image: '',summary: ``,slug: ""},
			B0873ZMKQT: {href: "https://amzn.to/3dCZzrk",nameProduct: `Frigidaire FFMV1846VS 30 `,image: '',summary: ``,slug: ""},
			B07XSCBSN5: {href: "https://amzn.to/3wz7hv0",nameProduct: `Amazon Smart Oven`,image: '',summary: ``,slug: ""},
			B07HYWDS7D: {href: "https://amzn.to/3mmCUTW",nameProduct: `Generator WGen9500`,image: '',summary: ``,slug: ""},
			B08N1GCTCB : {href: "https://amzn.to/3fL8zgF",nameProduct: `Briggs & Stratton Q6500 Generator`,image: '',summary: ``,slug: ""},
			B085FWK6JT: {href: "https://amzn.to/3utYlFM",nameProduct: `Generator Briggs & Stratton S5500 5500W`,image: '',summary: ``,slug: ""},
			B07554PR77 : {href: "https://amzn.to/39MtfRs",nameProduct: `Outland camping kitchen`,image: '',summary: ``,slug: ""},
			B01FUZKFLS: {href: "https://amzn.to/39IZQYn",nameProduct: `Eurosteam Iron steam irons`,image: '',summary: ``,slug: ""},
			B0028AYQDC : {href: "https://amzn.to/3cTxHzZ",nameProduct: `Whynter ARC-14S 14,000 BTU air conditioner`,image: '',summary: ``,slug: ""},
			B07BT9K6WQ: {href: "https://amzn.to/3rVsxHS",nameProduct: `Minka-Aire F844 ceiling fan`,image: '',summary: ``,slug: ""},
			B07F7M1XTH : {href: "https://amzn.to/3uoFnA8",nameProduct: `Minka-Aire F896 Outdoor Ceiling Fan`,image: '',summary: ``,slug: ""},
			B01HN1WMSG: {href: "https://amzn.to/3uwo9kx",nameProduct: `Outdoor ceiling fan Monte Carlo`,image: '',summary: ``,slug: ""},
			B083G9WVNC: {href: "https://amzn.to/3dzhG1g",nameProduct: `Panda PAN6320W Portable Machine`,image: '',summary: ``,slug: ""},
			B00SMLKEPA: {href: "https://amzn.to/3wrU6wd",nameProduct: `Dyson heating fan (61874-01)`,image: '',summary: ``,slug: ""},
			B08CFSZLQ4: {href: "https://amzn.to/39MHu95",nameProduct: `Google Pixel 4a phone`,image: '',summary: ``,slug: ""},
			B07DYSJT45: {href: "https://amzn.to/3wwwKFD",nameProduct: `UV UPANG Plus bottle sterilizer`,image: '',summary: ``,slug: ""},
			B00YDZI9BA : {href: "https://amzn.to/3mp5wMp",nameProduct: `Rotary hammer drill DEWALT`,image: '',summary: ``,slug: ""},
			B0866Y33PL: {href: "https://amzn.to/3mrw2oC",nameProduct: `Midea U Inverter Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B07HYZ2GM8: {href: "https://amzn.to/3wwJTOY",nameProduct: `Moccamaster coffee machine`,image: '',summary: ``,slug: ""},
			B08FVFY9BG: {href: "https://amzn.to/3rYkeLw",nameProduct: `SD-6513W Energy Star Portable Dishwasher`,image: '',summary: ``,slug: ""},
			B00J59XOJG: {href: "https://amzn.to/3cTuNLH",nameProduct: `BRIS 1.2mm PVC 12.5 ft Inflatable Boat`,image: '',summary: ``,slug: ""},
			B00J59XOJG: {href: "https://amzn.to/3cTuNLH",nameProduct: `BRIS 1.2mm PVC 12.5 ft Inflatable Boat`,image: '',summary: ``,slug: ""},
			B07VDVDHZ9: {href: "https://amzn.to/2OvGE9q",nameProduct: `Philips Espresso 3200 coffee machine`,image: '',summary: ``,slug: ""},
			B07SSVH7T1: {href: "https://amzn.to/3mnSn6a",nameProduct: `Calphalon Temp IQ Espresso Machine`,image: '',summary: ``,slug: ""},
			B088SH9V4G: {href: "https://amzn.to/3fPzfge",nameProduct: `Dell Inspiron All in One 5490 `,image: '',summary: ``,slug: ""},
			B00N2941OW: {href: "https://amzn.to/31NzSic",nameProduct: `Master water filtration system HMF2SmgCC`,image: '',summary: ``,slug: ""},
			B00SGGT14Q: {href: "https://amzn.to/3sPzyLL",nameProduct: `APEC pH + High output 90 GPD Drinking water `,image: '',summary: ``,slug: ""},
			B00K89EHES: {href: "https://amzn.to/31NeZng",nameProduct: `Rinnai Vent Free Fan Convector`,image: '',summary: ``,slug: ""},
			B002VXDCHW: {href: "https://amzn.to/3rUHme3",nameProduct: `IQAir HealthPro Plus Home HEPA Air Purifier`,image: '',summary: ``,slug: ""},
			B01JHI66VC: {href: "https://amzn.to/3sTpO32",nameProduct: `Airbourne HEPA cleaning machine`,image: '',summary: ``,slug: ""},
			B07DNCCJFN: {href: "https://amzn.to/31ORz0G",nameProduct: `Honeywell, Energy Star Dehumidifier TP50WK`,image: '',summary: ``,slug: ""},
			B079KRLHBT: {href: "https://amzn.to/2PvEfft",nameProduct: `RV Generac GP3500iO generator`,image: '',summary: ``,slug: ""},
			B01N4HPIYR: {href: "https://amzn.to/39KovMc",nameProduct: `Vitamix A2500 Ascent Series Blender`,image: '',summary: ``,slug: ""},
			B07S3XFND1: {href: "https://amzn.to/3cRzlSz",nameProduct: `Blender Breville BBL920BSS`,image: '',summary: ``,slug: ""},
			B00DS4767K: {href: "https://amzn.to/3wxeXxZ",nameProduct: `Breville Barista Express Coffee Machine`,image: '',summary: ``,slug: ""},
			B00667H8CE: {href: "https://amzn.to/3fLbC8B",nameProduct: `Bissell BigGreen  Cleaning  Extractor Machine`,image: '',summary: ``,slug: ""},
			B089N4WC3L: {href: "https://amzn.to/3uqOzUz",nameProduct: `Lenovo IdeaCentre AIO 3 Computer`,image: '',summary: ``,slug: ""},
			B089N4WC3L: {href: "https://amzn.to/3uqOzUz",nameProduct: `Lenovo IdeaCentre AIO 3 Computer`,image: '',summary: ``,slug: ""},
			B07ZPNFQZC: {href: "https://amzn.to/2PDHEZA",nameProduct: `RDR323 RCA clothes dryer`,image: '',summary: ``,slug: ""},
			B079KRLHBT: {href: "https://amzn.to/31PVvyn",nameProduct: `Generac generator GP3500iO`,image: '',summary: ``,slug: ""},
			B01MRDNXPL: {href: "https://amzn.to/3rRlnV7",nameProduct: `Dometic CFX28 12v Electric Powered Coole`,image: '',summary: ``,slug: ""},
			B0896Q81TF: {href: "https://amzn.to/3s32tLj",nameProduct: `TCL 14P31 portable-air-conditioner`,image: '',summary: ``,slug: ""},
			B01KUZO8BQ: {href: "https://amzn.to/3mqgnWE",nameProduct: `DJI RoboMaster S1 `,image: '',summary: ``,slug: ""},
			B01C9RIACG: {href: "https://amzn.to/3rUo48u",nameProduct: `Coway Airmega 400 Smart Air Purifier`,image: '',summary: ``,slug: ""},
			B01F4BANOM: {href: "https://amzn.to/3rUIGO3",nameProduct: `Alen BreatheSmart Room Air Purifier`,image: '',summary: ``,slug: ""},
			B0047R8NQK: {href: "https://amzn.to/2R38bje",nameProduct: `AIRHEAD Angler Bay Inflatable Boat`,image: '',summary: ``,slug: ""},
			B08GKVL7FN: {href: "https://amzn.to/3h305lV",nameProduct: `Bang & Olufsen wireless Bluetooth speaker`,image: '',summary: ``,slug: ""},
			B0846LGKRH: {href: "https://amzn.to/3t04GHP",nameProduct: `Bang & Olufsen Beosound wireless speakers 2`,image: '',summary: ``,slug: ""},
			B01N5G8USQ: {href: "https://amzn.to/3eLa1xg",nameProduct: `Bang & Olufsen Beoplay M5 wireless speaker`,image: '',summary: ``,slug: ""},
			B07P97CD5T: {href: "https://amzn.to/3u6hMEJ",nameProduct: `Miele Gray Classic C1 Pure vacuum cleaner`,image: '',summary: ``,slug: ""},
			B0869L1326: {href: "https://amzn.to/3xBgtzF",nameProduct: `ASUS VivoBook 15 Thin and Light Laptop`,image: '',summary: ``,slug: ""},
			B0863D15R6: {href: "https://amzn.to/3353kAI",nameProduct: `Apple iPad Pro`,image: '',summary: ``,slug: ""},
			B0009NU5YY: {href: "https://amzn.to/3e0Fe0p",nameProduct: `Char-Griller E1224 Smokin Pro 830 Square`,image: '',summary: ``,slug: ""},
			B089YSKJY6: {href: "https://amzn.to/3eIkfi7",nameProduct: `COMFEE’ 1.6 Cu.ft Portable Washing Machine`,image: '',summary: ``,slug: ""},
			B085SV35MT: {href: "https://amzn.to/3vtNRGB",nameProduct: `Panasonic HomeChef Microwave Oven`,image: '',summary: ``,slug: ""},
			B001HWQG2G: {href: "https://amzn.to/3u6in9r",nameProduct: `TPI Corporation FES15483E Heat Wave `,image: '',summary: ``,slug: ""},
			B06Y5T9HLP: {href: "https://amzn.to/3t6A3jZ",nameProduct: `Jura A1 Super Automatic Coffee Machine`,image: '',summary: ``,slug: ""},
			B07G3XYR3R: {href: "https://amzn.to/3e2q2Qj",nameProduct: `Saeco Xelsis Super Automatic Espresso Machine`,image: '',summary: ``,slug: ""},
			B0758JHZM3: {href: "https://amzn.to/2Rej6qh",nameProduct: `Vitamix E310 Explorian Blender`,image: '',summary: ``,slug: ""},
			B00BY0A8Y8: {href: "https://amzn.to/3xABRFj",nameProduct: `Vitamix 5200 Blender`,image: '',summary: ``,slug: ""},
			B01N4HPJV3: {href: "https://amzn.to/3e2BtHK",nameProduct: `Vitamix A2300 Ascent Series Blender`,image: '',summary: ``,slug: ""},
			B074HN2LCX: {href: "https://amzn.to/3xCiQCs",nameProduct: `CMC-Classic Model Cars Mercedes-Benz 300Sl`,image: '',summary: ``,slug: ""},
			B07BYK2ZPP: {href: "https://amzn.to/2QLTxgt",nameProduct: `Champion 4375/3500-Watt Portable Generator`,image: '',summary: ``,slug: ""},
			B07XZX5FTR: {href: "https://amzn.to/3aRZHTb",nameProduct: `WEN 56203i Portable Inverter Generator`,image: '',summary: ``,slug: ""},
			B01A6I1WUC: {href: "https://amzn.to/3xAQ2Kw",nameProduct: `Briggs & Stratton P2200 Generator`,image: '',summary: ``,slug: ""},
			B07KH6P3GX: {href: "https://amzn.to/3e2Ca3O",nameProduct: `Lamborghini Aventador S New Model Car`,image: '',summary: ``,slug: ""},
			B07PDXKSGJ: {href: "https://amzn.to/3gPso7d",nameProduct: `MIDEA EasyCool Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B00BWYO53G: {href: "https://amzn.to/3aOnBim",nameProduct: `Honeywell HPA300 True HEPA Air Purifier`,image: '',summary: ``,slug: ""},
			B08R7QW6NP: {href: "https://amzn.to/3xCjBvi",nameProduct: `Odyssey 5-Blade Smart Flush Mount Ceiling Fan`,image: '',summary: ``,slug: ""},
			B005C5DWQW: {href: "https://amzn.to/331ljrY",nameProduct: `YAMAHA 230 Series Tower Mooring Boat`,image: '',summary: ``,slug: ""},
			B01DLPUWL2: {href: "https://amzn.to/2RcAIms",nameProduct: `Air conditioner BLACK + DECKER BPACT08WT`,image: '',summary: ``,slug: ""},
			B01DLPUWHQ: {href: "https://amzn.to/3nyGMC0",nameProduct: `BLACK+DECKER BPACT14WT  Air Conditioner`,image: '',summary: ``,slug: ""},
			B08677DCKN: {href: "https://amzn.to/2QKNxVp",nameProduct: `Midea U Inverter Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B016XY88AA: {href: "https://amzn.to/3e4XYfq",nameProduct: `Mai Cook Inox Induction cooker`,image: '',summary: ``,slug: ""},
			B00SF1BGUO: {href: "https://amzn.to/3aNF8Yc",nameProduct: `PK Grills PKl Portable Grill `,image: '',summary: ``,slug: ""},
			B07PBFKXW9: {href: "https://amzn.to/330RxDH",nameProduct: `Sony XB72 High Power Home Audio System`,image: '',summary: ``,slug: ""},
			B07JHP2VNF: {href: "https://amzn.to/2RccUiy",nameProduct: `JBL Charge 4 Portable Bluetooth Speaker`,image: '',summary: ``,slug: ""},
			B073WJL99W: {href: "https://amzn.to/330HMFB",nameProduct: `Blueair Blue Pure 211+ Air Purifier 3 Stages `,image: '',summary: ``,slug: ""},
			B01M65VK6G: {href: "https://amzn.to/3u7PHN4",nameProduct: `BreatheSmart FLEX Alen air purifier`,image: '',summary: ``,slug: ""},
			B07M8P1RFW: {href: "https://amzn.to/3eNL0BY",nameProduct: `A-iPower SUA2000iV Portable Inverter Generator`,image: '',summary: ``,slug: ""},
			B002RWK9N2: {href: "https://amzn.to/3vsvPog",nameProduct: `YAMAHA EF2000iSv2 Gas Powered Portable Inverter`,image: '',summary: ``,slug: ""},
			B07PTNTRRJ: {href: "https://amzn.to/3vyFrxE",nameProduct: `WEN 56380i Portable Inverter Generator`,image: '',summary: ``,slug: ""},
			B089TQB1RB: {href: "https://amzn.to/2RwvB0X",nameProduct: `Shark AZ2002 Vertex DuoClean vacuum cleaner`,image: '',summary: ``,slug: ""},
			B00EAY540S: {href: "https://amzn.to/2QySksY",nameProduct: `Panda 110V Portable Laundry Clothes Dryer`,image: '',summary: ``,slug: ""},
			B08PG4W932: {href: "https://amzn.to/3osZT0T",nameProduct: `Acer Aspire 5 A515-56-50RS`,image: '',summary: ``,slug: ""},
			B088W1QJP1: {href: "https://amzn.to/3hHP0Xx",nameProduct: `Skytech Archangel Gaming Computer`,image: '',summary: ``,slug: ""},
			B0787GML22: {href: "https://amzn.to/3wh41n7",nameProduct: `Midea equipment 1434N0A Microwave`,image: '',summary: ``,slug: ""},
			B00J0S0JGS: {href: "https://amzn.to/3u02IYp",nameProduct: `Sevylor Coleman Colorado 2-Person Kayak`,image: '',summary: ``,slug: ""},
			B0839PFC8G: {href: "https://amzn.to/3hBpH9F",nameProduct: `Aquaglide McKenzie 105 Inflatable Kayak`,image: '',summary: ``,slug: ""},
			B084SY2D84: {href: "https://amzn.to/3v1ctXr",nameProduct: `DeLonghi 14000 BTU Portable Air Conditioner`,image: '',summary: ``,slug: ""},
			B074F8TZNH: {href: "https://amzn.to/3u0EjBS",nameProduct: `Brother SE600 Sewing and Embroidery Machine`,image: '',summary: ``,slug: ""},
			B008G1DJ9Y: {href: "https://amzn.to/3bDLGsu",nameProduct: `Brother HC1850 Sewing and Quilting Machine`,image: '',summary: ``,slug: ""},
			B07C9RQP1D: {href: "https://amzn.to/3ylxBd7",nameProduct: `Brother SE1900 Sewing and Embroidery Machine`,image: '',summary: ``,slug: ""},
			B07DLGCVRP: {href: "https://amzn.to/3oyvvCm",nameProduct: `Brother SE625 Sewing and Embroidery Machine`,image: '',summary: ``,slug: ""},
			B07QMWZ6PT: {href: "https://amzn.to/3tYaGBb",nameProduct: `DeLonghi La Specialista Espresso Machine`,image: '',summary: ``,slug: ""},
			B08FRQGSPN: {href: "https://amzn.to/3veCcMt",nameProduct: `Technivorm Moccamaster Coffee Maker`,image: '',summary: ``,slug: ""},
			B01FHQVY8I: {href: "https://amzn.to/2RxZez9",nameProduct: `Blendtec Classic 575 Blender`,image: '',summary: ``,slug: ""},
			B00DWKEHU4: {href: "https://amzn.to/3tYcpGF",nameProduct: `Keurig K155 Office Pro Commercial Coffee Maker`,image: '',summary: ``,slug: ""},
			B00004RDF0: {href: "https://amzn.to/2Rp5g5c",nameProduct: `Lello 4080 Musso Lussino Ice Cream Maker`,image: '',summary: ``,slug: ""},
			B085B3GCCK: {href: "https://amzn.to/3uacuHD",nameProduct: `MSI Prestige 14 A10SC Notebook`,image: '',summary: ``,slug: ""},
			B08K9G7939: {href: "https://amzn.to/3wkRyPE",nameProduct: `MSI Summit E14 A11SCS Laptops`,image: '',summary: ``,slug: ""},
			B07G3XYR3R: {href: "https://amzn.to/3hEK5H0",nameProduct: `Saeco Xelsis Automatic Espresso Machine`,image: '',summary: ``,slug: ""},
			B01F4WT8XS: {href: "https://amzn.to/2S5QUqn",nameProduct: `DeLonghi Eletta Digital Espresso Machine`,image: '',summary: ``,slug: ""},
			B086Z3S3MY: {href: "https://amzn.to/3fyypTg",nameProduct: `Samsung Galaxy Tab S6 Lite`,image: '',summary: ``,slug: ""},
			B08GKVL7FN: {href: "https://amzn.to/3hzlpzz",nameProduct: `Bang & Olufsen Beolit 20 Bluetooth Speaker`,image: '',summary: ``,slug: ""},
			B089YSKJY6: {href: "https://amzn.to/2QuNUDg",nameProduct: `COMFEE 1.6 Cu.ft Portable Washing Machine`,image: '',summary: ``,slug: ""},
			B07JKM5937: {href: "https://amzn.to/3wnby47",nameProduct: `Kuryakyn 2720 MTX Road Thunder Sound Bar for motorcycle`,image: '',summary: ``,slug: ""},
			B07B4WM5H1: {href: "https://amzn.to/2Sa25Ot",nameProduct: `ELAC Debut 2.0 SUB3010 Powered Subwoofer `,image: '',summary: ``,slug: ""},
			B07J4HY7GS: {href: "https://amzn.to/3ftMelV",nameProduct: `Marshall Acton II Wireless Smart Speaker`,image: '',summary: ``,slug: ""},
			B01FFRR2PS: {href: "https://amzn.to/3wlJz4u",nameProduct: `Blendtec Classic 575 Blender`,image: '',summary: ``,slug: ""},
			B00TKRQWS8: {href: "https://amzn.to/3fwuXsh",nameProduct: `Blendtec Total Classic Original Blender`,image: '',summary: ``,slug: ""},
			B08194ZQ4N: {href: "https://amzn.to/3ymSzYZ",nameProduct: `Medify Air MA-40 Air Purifier`,image: '',summary: ``,slug: ""},
			B08XJQBZVZ: {href: "https://amzn.to/3wk5yJm",nameProduct: `Honeywell Compact Portable Air Conditioner`,image: '',summary: ``,slug: ""},
			B08NQ17JYJ: {href: "https://amzn.to/3owJgBp",nameProduct: `Alienware m15 R3 Gaming Laptop`,image: '',summary: ``,slug: ""},
			B07CLKMRM1 : {href: "https://amzn.to/3tYejHj",nameProduct: `Yamaha WX-021 MusicCast 20 Wireless Speaker`,image: '',summary: ``,slug: ""},
			B07H7DRWJN: {href: "https://amzn.to/3ouOOMI",nameProduct: `Marshall Stanmore II Smart Speaker`,image: '',summary: ``,slug: ""},
			B01M24U0CJ: {href: "https://amzn.to/3bBH2eA",nameProduct: `DEWALT DCH273B 20V Hammer drill`,image: '',summary: ``,slug: ""},
			B07WVV36P1: {href: "https://amzn.to/3bCZow6",nameProduct: `JCB Tools - JCB 20V Hammer drill`,image: '',summary: ``,slug: ""},
			B07BTR5VXY: {href: "https://amzn.to/3oCeO8X",nameProduct: `Yard Machines 132cc Lawn Mowers`,image: '',summary: ``,slug: ""},
			B00GX9WNP2: {href: "https://amzn.to/3hzwzV3",nameProduct: `Greenworks 40V 20-Inch Lawn Mower`,image: '',summary: ``,slug: ""},
			B00OZWX100: {href: "https://amzn.to/3wjxoFq",nameProduct: `SINGER Heavy Duty 4452 Sewing Machine`,image: '',summary: ``,slug: ""},
			B001BG08DQ: {href: "https://amzn.to/3hCW08f",nameProduct: `JUKI MO654DE  Serger Sewing Machine`,image: '',summary: ``,slug: ""},
			B091TXLW8W: {href: "https://amzn.to/3f0dvxB",nameProduct: `Greenworks MO80L410 Pro 80V Lawn mower`,image: '',summary: ``,slug: ""},
			B08C5J34T5: {href: "https://amzn.to/3bz19u7",nameProduct: `Canon imagePROGRAF PRO-300 Printer`,image: '',summary: ``,slug: ""},
			B01GQU3EUU: {href: "https://amzn.to/3fssUFP",nameProduct: `Honda - General Purpose Water Pump`,image: '',summary: ``,slug: ""},
			B00381T8LU: {href: "https://amzn.to/3ypgVkP",nameProduct: `NorthStar High-Pressure Water Pump`,image: '',summary: ``,slug: ""},
			B0892QWHKQ: {href: "https://amzn.to/3wlWzaj",nameProduct: `Samsung QN55Q60TA 55 Smart TV`,image: '',summary: ``,slug: ""},
			B07N76WN9Z: {href: "https://amzn.to/3wi1NUz",nameProduct: `Generac 7676 GP8000E Portable Generator`,image: '',summary: ``,slug: ""},
			B07Q1DLKBG: {href: "https://amzn.to/3v1byXf",nameProduct: `Westinghouse WGen9500DF Portable Generator`,image: '',summary: ``,slug: ""},
			B08HGS82P6: {href: "https://amzn.to/3frYZO8",nameProduct: `Champion 200986 Generator`,image: '',summary: ``,slug: ""},
			B005GXPOCK: {href: "https://amzn.to/2RwBBXx",nameProduct: `Brother CS5055PRW Sewing Machine`,image: '',summary: ``,slug: ""},
			B005GXPO70: {href: "https://amzn.to/3bDAegI",nameProduct: `Brother Coverstitch Serger`,image: '',summary: ``,slug: ""},
			B00916Y4YM: {href: "https://amzn.to/2Rp8tSi",nameProduct: `Janome HD3000 Heavy-Duty Sewing Machine`,image: '',summary: ``,slug: ""},
			B07KZ4ZBT5: {href: "https://amzn.to/3hGVVjI",nameProduct: `Breville Juicer BJE830BSS Juice Founatin Cold XL`,image: '',summary: ``,slug: ""},
			B071QYVR17: {href: "https://amzn.to/3f0y9xx",nameProduct: `Tribest Greenstar Pro Juice Extractor`,image: '',summary: ``,slug: ""},
			B0176L0T6U: {href: "https://amzn.to/3u2fTrC",nameProduct: `Tribest GSE 5050 Greenstar Elite Juicer`,image: '',summary: ``,slug: ""},
			B005Z48VVQ: {href: "https://amzn.to/3wotF9T",nameProduct: `Tribest Green Star Elite GSE 5000 Juicer`,image: '',summary: ``,slug: ""},
			B01M0N8256: {href: "https://amzn.to/340w5iJ",nameProduct: `DuroMax XP12000EH Generator`,image: '',summary: ``,slug: ""},
			B08PJY5PV1 : {href: "https://amzn.to/3hDEnVJ",nameProduct: `Ice machine ADT Ice Mahcine`,image: '',summary: ``,slug: ""},
			B08PJY5PV1 : {href: "https://amzn.to/3hDEnVJ",nameProduct: `Commercial Ice Machine ADT Ice Mahcine`,image: '',summary: ``,slug: ""},
			B009OZ62IG: {href: "https://amzn.to/2SXzA77",nameProduct: `Breville BCI600XL Smart Scoop Ice Cream Maker`,image: '',summary: ``,slug: ""},
			B0869L1326: {href: "https://amzn.to/3hDI7qk",nameProduct: `ASUS VivoBook 15 Thin and Light Laptop`,image: '',summary: ``,slug: ""},
			B00170HVFO: {href: "https://amzn.to/3ckXwbE",nameProduct: `Reliable 3000IS Steam Ironing`,image: '',summary: ``,slug: ""},
			B00061J2B6: {href: "https://amzn.to/3vTCtEz",nameProduct: `Steamfast SF-680 Steam Press`,image: '',summary: ``,slug: ""},
			B01IY813XC: {href: "https://amzn.to/3yXHZZ3",nameProduct: `Snapper XD 82V MAX 21" Lawn Mower`,image: '',summary: ``,slug: ""},
			B07BY88V1Q: {href: "https://amzn.to/3ijsFzU",nameProduct: `WORX WG779 40V Lawn Mower`,image: '',summary: ``,slug: ""},
			B07SZ1VC7W: {href: "https://amzn.to/3vTfycx",nameProduct: `Bugatti Chiron Argent Silver 1/18 Model Car `,image: '',summary: ``,slug: ""},
			B0177IUY3U: {href: "https://amzn.to/3fOZ9Aq",nameProduct: `Daron Skymarks Thai A380 Airplane Model`,image: '',summary: ``,slug: ""},
			B08BSHC92S: {href: "https://amzn.to/3potKbl",nameProduct: `Koenigsegg One 1/18 Model Car`,image: '',summary: ``,slug: ""},
			B01KUZO8BQ: {href: "https://amzn.to/3chrmgU",nameProduct: `DJI RoboMaster S1`,image: '',summary: ``,slug: ""},
			B08HJHP6Y6: {href: "https://amzn.to/2SXyLeO",nameProduct: `Xiaomi Mi 10T`,image: '',summary: ``,slug: ""},
			B08XX4P7LB: {href: "https://amzn.to/3fSgbh7",nameProduct: `Samsung Galaxy A52 5G`,image: '',summary: ``,slug: ""},
			B091NBQZNY: {href: "https://amzn.to/3x009aI",nameProduct: `Dell Inspiron 15 Business Laptop`,image: '',summary: ``,slug: ""},
			B08JGX61H7: {href: "https://amzn.to/34QGgH8",nameProduct: `DJI Mini 2 Fly More Combo`,image: '',summary: ``,slug: ""},
			B086XCGMN7: {href: "https://amzn.to/3uN7Rn2",nameProduct: `DJI Mavic Air 2 Fly More Combo`,image: '',summary: ``,slug: ""},
			B07H5WT1H9: {href: "https://amzn.to/34MC1w4",nameProduct: `DJI Mavic 2 Pro Drone Quadcopter`,image: '',summary: ``,slug: ""},
			B0832YH9Y9: {href: "https://amzn.to/3fUAqe9",nameProduct: `Blendtec Stealth 885 Commercial Blender`,image: '',summary: ``,slug: ""},
			B00GPRPWAU: {href: "https://amzn.to/3pplTdf",nameProduct: `Blendtec Total Classic Original Blender`,image: '',summary: ``,slug: ""},
			B00LFVV8CM: {href: "https://amzn.to/3vSEe4Y",nameProduct: `Vitamix Professional Series 750 Blender`,image: '',summary: ``,slug: ""},
			B088G23N6Y: {href: "https://amzn.to/2RnLlmX",nameProduct: `Zojirushi Rice Cooker`,image: '',summary: ``,slug: ""},
			B089TQ82WT: {href: "https://amzn.to/34MnoZE",nameProduct: `Ninja Grill FG551 Foodi Smart XL`,image: '',summary: ``,slug: ""},
			B003YFHPGK: {href: "https://amzn.to/2Rpc2I5",nameProduct: `Kenyon B70080 Electric Grill`,image: '',summary: ``,slug: ""},
			B07JZV24HV: {href: "https://amzn.to/2T1kE8g",nameProduct: `Char-Broil 463377319 Gas Grill`,image: '',summary: ``,slug: ""},
			B08WYHGSLB: {href: "https://amzn.to/3po0RvM",nameProduct: `New Dell Inspiron 5000 Desktop`,image: '',summary: ``,slug: ""},
			B089HR6CQP: {href: "https://amzn.to/34MIozl",nameProduct: `Dell Gaming G3 15 3500 `,image: '',summary: ``,slug: ""},
			B071R7NGTD: {href: "https://amzn.to/3fSDQxN",nameProduct: `Jabra Speak 710 UC Bluetooth Speaker`,image: '',summary: ``,slug: ""},
			B07C879SMB: {href: "https://amzn.to/2TKnHC4",nameProduct: `Mercedes Maybach S 600 Pullman 1/18 Model Car `,image: '',summary: ``,slug: ""},
			B084GFNQGK: {href: "https://amzn.to/3uVlbpr",nameProduct: `1/18 Model Car G63 AMG 6X6`,image: '',summary: ``,slug: ""},
			B08P1JJSDL: {href: "https://amzn.to/3g7C1fy",nameProduct: `Robit Robot Vacuum Cleaner V7S `,image: '',summary: ``,slug: ""},
			B08C74PLHP: {href: "https://amzn.to/3plrhOR",nameProduct: `Shark IQ Robot Vacuum AV1002AE`,image: '',summary: ``,slug: ""},
			B08DLRYHKY: {href: "https://amzn.to/3uSHrjN",nameProduct: `Shark AV1010AE IQ Robot Vacuum `,image: '',summary: ``,slug: ""},
			B08XJQBZVZ: {href: "https://amzn.to/2RrgC8I",nameProduct: `Honeywell Compact Portable Air Conditioner`,image: '',summary: ``,slug: ""},
			B01AA8WOAK: {href: "https://amzn.to/3ppkVhu",nameProduct: `Whynter Elite ARC-122DS Portable Air Conditioner`,image: '',summary: ``,slug: ""},
			B01D3FOCVQ: {href: "https://amzn.to/3uWevau",nameProduct: `LG LW1216HR Window-Mounted Air Conditioner`,image: '',summary: ``,slug: ""},
			B08677DCKN: {href: "https://amzn.to/34Mk68V",nameProduct: `Midea U Inverter Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B06XQ2THY8: {href: "https://amzn.to/3gqHu1d",nameProduct: `Greenworks 40V 21 inch Lawn Mower`,image: '',summary: ``,slug: ""},
			B0857JMSTB: {href: "https://amzn.to/3uVlArX",nameProduct: `Lawn mower EGO Power + LM2130SP`,image: '',summary: ``,slug: ""},
			B084SY2D84: {href: "https://amzn.to/3cjFzdc",nameProduct: `DeLonghi 14000 BTU Portable Air Conditioner`,image: '',summary: ``,slug: ""},
			B08VKV5WQ1: {href: "https://amzn.to/34SywUZ",nameProduct: `Acer Predator Helios 300 Gaming Laptop `,image: '',summary: ``,slug: ""},
			B08SJDNLV8: {href: "https://amzn.to/3pqIoyO",nameProduct: `Razer Blade 15 Base Gaming Laptop`,image: '',summary: ``,slug: ""},
			B00IINNKRQ: {href: "https://amzn.to/3po1GVo",nameProduct: `Honeywell 525 CFM Portable Evaporative Cooler`,image: '',summary: ``,slug: ""},
			B08F7PTF54: {href: "https://amzn.to/3plGuiG",nameProduct: `Oculus Quest 2 Virtual Reality Headset`,image: '',summary: ``,slug: ""},
			B01C9RIACG: {href: "https://amzn.to/3uQbSHf",nameProduct: `Coway Airmega 400 Smart Air Purifier`,image: '',summary: ``,slug: ""},
			B07LCSK4JY: {href: "https://amzn.to/3wVO3iM",nameProduct: `BLACK+DECKER BPWH84W Washer Portable`,image: '',summary: ``,slug: ""},
			B00EAY540S: {href: "https://amzn.to/2T0TJcJ",nameProduct: `Panda Portable  Laundry Clothes Dryer`,image: '',summary: ``,slug: ""},
			B01K8S7OUW: {href: "https://amzn.to/3fPfh50",nameProduct: `Big Ass Fans Haiku L Smart Ceiling Fan`,image: '',summary: ``,slug: ""},
			B089N4WC3L: {href: "https://amzn.to/3uTarIa",nameProduct: `Lenovo IdeaCentre AIO 3 Computer`,image: '',summary: ``,slug: ""},
			B08KH2Q1FG: {href: "https://amzn.to/3v2iB17",nameProduct: `ASUS TUF Gaming Laptop`,image: '',summary: ``,slug: ""},
			B08637NV8M: {href: "https://amzn.to/3vXscHu",nameProduct: `Apple iPad Pro `,image: '',summary: ``,slug: ""},
			B085WSCTL2: {href: "https://amzn.to/3pkaADm",nameProduct: `Apple iPad Mini`,image: '',summary: ``,slug: ""},
			B08BG8DVGJ: {href: "https://amzn.to/3wZy5nW",nameProduct: `SAMSUNG Galaxy Tab A`,image: '',summary: ``,slug: ""},
			B089YSKJY6: {href: "https://amzn.to/3pWtccK",nameProduct: `COMFEE’ 1.6 Cu.ft Portable Washing Machine`,image: '',summary: ``,slug: ""},
			B00MWXSFM8: {href: "https://amzn.to/3gqw3HM",nameProduct: `Midea 3.1 Cu. Ft. Compact Refrigerator`,image: '',summary: ``,slug: ""},
			B07X9JW274: {href: "https://amzn.to/35or7wG",nameProduct: `Shinco 10,000 BTU Portable Air Conditioners`,image: '',summary: ``,slug: ""},
			B00MVVITWC: {href: "https://amzn.to/3wu08Mp",nameProduct: `Midea MRC04M3AWW Single Door Chest Freezer`,image: '',summary: ``,slug: ""},
			B07SBK9LRY: {href: "https://amzn.to/3vqV9up",nameProduct: `HP Elite Desktop PC Computer`,image: '',summary: ``,slug: ""},
			B085SV35MT: {href: "https://amzn.to/3vtlBno",nameProduct: `Panasonic NN-CD87KS HomeChef 4-in-1 Oven`,image: '',summary: ``,slug: ""},
			B013RO89N0: {href: "https://amzn.to/2TAHkfI",nameProduct: `Smeg BLF01BLUS retro blender`,image: '',summary: ``,slug: ""},
			B07G6B7VGV: {href: "https://amzn.to/35pcJEz",nameProduct: `Kids Ride-ON CAR Truck Explorer 12V`,image: '',summary: ``,slug: ""},
			B093NZL14M: {href: "https://amzn.to/3gBrpWq",nameProduct: `Rolls Royce Ghost English White 1/18`,image: '',summary: ``,slug: ""},
			B08PBQ8151: {href: "https://amzn.to/2SvhTfC",nameProduct: `Dodge Challenger SRT Hellcat`,image: '',summary: ``,slug: ""},
			B00JGCAHWE: {href: "https://amzn.to/3vut4CC",nameProduct: `Juki HZL-F600 sewing machine`,image: '',summary: ``,slug: ""},
			B07FWYLKSG: {href: "https://amzn.to/3pUYIbe",nameProduct: `Shark ZS351 Rocket ultra-light vacuum cleaner`,image: '',summary: ``,slug: ""},
			B089TQB1RB: {href: "https://amzn.to/3vrT15O",nameProduct: `Shark AZ2002 Vertex DuoClean PowerFins Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B072BZ74VK: {href: "https://amzn.to/3wwbbEO",nameProduct: `SereneLife Inflatable Stand Up Paddle Board`,image: '',summary: ``,slug: ""},
			B08BTNGBCG: {href: "https://amzn.to/3gABC5w",nameProduct: `Inflatable Sport Boats - Swordfish`,image: '',summary: ``,slug: ""},
			B00CTCACOQ: {href: "https://amzn.to/3vA8YqI",nameProduct: `BRIS 9.8 ft Inflatable Boat Inflatable`,image: '',summary: ``,slug: ""},
			B08GJQ17CF: {href: "https://amzn.to/3groD75",nameProduct: `Meepo V3 Electric Skateboard`,image: '',summary: ``,slug: ""},
			B08GJR3T43: {href: "https://amzn.to/3gt4b67",nameProduct: `Meepo Mini 2 Electric Skateboard`,image: '',summary: ``,slug: ""},
			B07GGTR2X6: {href: "https://amzn.to/2S4YXEc",nameProduct: `Teamgee H5 37 Electric Skateboard`,image: '',summary: ``,slug: ""},
			B08LZHWX95: {href: "https://amzn.to/3gtte8R",nameProduct: `Teamgee H20mini Electric Skateboard`,image: '',summary: ``,slug: ""},
			B07SDQ79X3: {href: "https://amzn.to/35r6mAM",nameProduct: `Electric scooters for adults `,image: '',summary: ``,slug: ""},
			B072BZ74VK: {href: "https://amzn.to/3grAQIV",nameProduct: `SereneLife Inflatable Stand Up Paddle Board`,image: '',summary: ``,slug: ""},
			B07CX6SW72: {href: "https://amzn.to/3gtfvyO",nameProduct: `SereneLife Premium Inflatable Stand Up Paddle Board`,image: '',summary: ``,slug: ""},
			B0843HK35B: {href: "https://amzn.to/2S4ZeHe",nameProduct: `Senville LETO air conditioner`,image: '',summary: ``,slug: ""},
			B083R2XKTS: {href: "https://amzn.to/3cKEL1q",nameProduct: `MRCOOL DIY 24k BTU 20 SEER Ductless Heat Pump Split System`,image: '',summary: ``,slug: ""},
			B00CMBTCHW: {href: "https://amzn.to/3wtn6Da",nameProduct: `Intex Mariner Inflatable Boat`,image: '',summary: ``,slug: ""},
			B07H8S6L5G: {href: "https://amzn.to/3qZ65yK",nameProduct: `Generac 7127 iQ3500 Generator`,image: '',summary: ``,slug: ""},
			B083KBKJ8Q: {href: "https://amzn.to/3hxFrds",nameProduct: `Jackery Explorer 1000 Solar Generator`,image: '',summary: ``,slug: ""},
			B08RS3J5YV: {href: "https://amzn.to/3e3Iw2O",nameProduct: `Dell XPS 8940 Desktop Computer `,image: '',summary: ``,slug: ""},
			B07BDQSTRV: {href: "https://amzn.to/3k1eUGP",nameProduct: `Nixie Tube Clock`,image: '',summary: ``,slug: ""},
			B083V76MM7: {href: "https://amzn.to/3yHN2f1",nameProduct: `Haier Serenity Series Air Conditioners`,image: '',summary: ``,slug: ""},
			B08QMMPSN2: {href: "https://amzn.to/3ANdRAl",nameProduct: `WAVEY BOARD Stand up paddle board`,image: '',summary: ``,slug: ""},
			B08723759H: {href: "https://amzn.to/3yKXSRv",nameProduct: `OnePlus 8 Glacial Green,​ 5G`,image: '',summary: ``,slug: ""},
			B07VTB2BF2: {href: "https://amzn.to/3hxYJPI",nameProduct: `HP Newest Lightweight Stream-14inch`,image: '',summary: ``,slug: ""},
			B08D6T5YSN: {href: "https://amzn.to/2T4ax2T",nameProduct: `GE Window Air Conditioner 6,000 BTU`,image: '',summary: ``,slug: ""},
			B07NGGDQLS: {href: "https://amzn.to/3wylkQy",nameProduct: `Miko 2: Playful Learning STEM Robot `,image: '',summary: ``,slug: ""},
			B085D45SZF: {href: "https://amzn.to/3hW2YUn",nameProduct: `iRobot Roomba i6+ (6550) Robot Vacuum`,image: '',summary: ``,slug: ""},
			B07GNPDMRP: {href: "https://amzn.to/3yP3jPx",nameProduct: `iRobot Roomba i7+ (7550) Robot Vacuum`,image: '',summary: ``,slug: ""},
			B07TYRGWSQ: {href: "https://amzn.to/2Vw2RqY",nameProduct: `FlashForge Adventurer 3 Lite FDM 3D Printer`,image: '',summary: ``,slug: ""},
			B07MDGSR2D: {href: "https://amzn.to/36tu6Vu",nameProduct: `Flycam Basic Flowline`,image: '',summary: ``,slug: ""},
			B08FJ79PW2: {href: "https://amzn.to/3e6XGEb",nameProduct: `Ruko F11Gim Drones `,image: '',summary: ``,slug: ""},
			B01JRTZVJE: {href: "https://amzn.to/2TPhqpf",nameProduct: `CUCKOO Electric Induction Heating Pressure Rice Cooker`,image: '',summary: ``,slug: ""},
			B08FJ79PW2: {href: "https://amzn.to/3yKH3pT",nameProduct: `Ruko F11Gim Drones `,image: '',summary: ``,slug: ""},
			B08DK5ZH44: {href: "https://amzn.to/3wwV7Sg",nameProduct: `GoPro HERO9 Black`,image: '',summary: ``,slug: ""},
			B08KSMKHF3: {href: "https://amzn.to/3AK4aCR",nameProduct: `Canon EOS 4000D DSLR Camera`,image: '',summary: ``,slug: ""},
			B08K7CKKB1: {href: "https://amzn.to/3wHpLbX",nameProduct: `Canon EOS 2000D (Rebel T7) DSLR Camera`,image: '',summary: ``,slug: ""},
			B07MV3P74D: {href: "https://amzn.to/2Uz9k3U",nameProduct: `Sony Alpha a6400 Mirrorless Camera`,image: '',summary: ``,slug: ""},
			B089W2MGD6: {href: "https://amzn.to/3kjfMaf",nameProduct: `Lenovo Flex 5 AMD Ryzen 7 4700U`,image: '',summary: ``,slug: ""},
			B0886L3CFV: {href: "https://amzn.to/3ARVTN2",nameProduct: `HP Stream 11.6-inch HD Laptop`,image: '',summary: ``,slug: ""},
			B08KH3FH15: {href: "https://amzn.to/2TVgoI0",nameProduct: `HP Pavilion x360 14 2-in-1 Laptop`,image: '',summary: ``,slug: ""},
			B08KGYDR16: {href: "https://amzn.to/3e6Y3i3",nameProduct: `HP Pavilion 15 Laptop`,image: '',summary: ``,slug: ""},
			B07FX73Y7H: {href: "https://amzn.to/3eBhUX9",nameProduct: `Ninja Hot and Cold Brewed System, Auto-iQ Tea and Coffee Maker`,image: '',summary: ``,slug: ""},
			B08YKHYCPW: {href: "https://amzn.to/3zv4C6D",nameProduct: `Lenovo IdeaPad 1 14 Laptop`,image: '',summary: ``,slug: ""},
			B08H4YTTLP: {href: "https://amzn.to/3Bopyh6",nameProduct: `ASUS VivoBook 15 F515 Laptop`,image: '',summary: ``,slug: ""},
			B07K85LXBK: {href: "https://amzn.to/2UWptR5",nameProduct: `Tovala Gen 2 Smart Steam Oven`,image: '',summary: ``,slug: ""},
			B08DVCNYJC: {href: "https://amzn.to/3BkLJ83",nameProduct: `Bose QuietComfort 35 Series 2 Gaming Headset`,image: '',summary: ``,slug: ""},
			B08TZRP19J: {href: "https://amzn.to/3irrGfn",nameProduct: `Bang & Olufsen Beoplay HX - Headphones `,image: '',summary: ``,slug: ""},
			B08L9V2YX1: {href: "https://amzn.to/3hTpOgg",nameProduct: `ULTIMATE EARS FITS True Wireless`,image: '',summary: ``,slug: ""},
			B07VR22832: {href: "https://amzn.to/3rmGWOC",nameProduct: `Farberware Dishwasher`,image: '',summary: ``,slug: ""},
			B07VMTF2Y4: {href: "https://amzn.to/3Bpx0IM",nameProduct: `Farberware Professional Dishwasher`,image: '',summary: ``,slug: ""},
			B07N6J8MQQ: {href: "https://amzn.to/2Uup9cr",nameProduct: `Breville the Q Countertop Blender`,image: '',summary: ``,slug: ""},
			B072JWYJMC: {href: "https://amzn.to/3kyyQ4g",nameProduct: `Jabra Evolve 75 UC Stereo`,image: '',summary: ``,slug: ""},
			B089N3YRZN: {href: "https://amzn.to/3kBm6d6",nameProduct: `GE Appliances 13,500 BTU Air conditioners`,image: '',summary: ``,slug: ""},
			B0868WSQLM: {href: "https://amzn.to/3rnQ3yT",nameProduct: `Friedrich Chill Premier Smart Air Conditioner`,image: '',summary: ``,slug: ""},
			B08TBWFR5M: {href: "https://amzn.to/2W2Mani",nameProduct: `Robot Vacuum Cleaner Uoni V980Plus`,image: '',summary: ``,slug: ""},
			B00R43I4EU: {href: "https://amzn.to/2Uoe50C",nameProduct: `Miele Complete C3 Marin Canister Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B085D4MFS8: {href: "https://amzn.to/3eBLUCc",nameProduct: `iRobot Roomba 692 Robot Vacuum`,image: '',summary: ``,slug: ""},
			B08M3B9754: {href: "https://amzn.to/3hRI1es",nameProduct: `Insta360 ONE X2 360 Camera`,image: '',summary: ``,slug: ""},
			B07RC8HPHL: {href: "https://amzn.to/3iwEOzQ",nameProduct: `OLYMPUS Tough TG-6 Waterproof Camera`,image: '',summary: ``,slug: ""},
			B01DLPUWL2: {href: "https://amzn.to/3eCccUI",nameProduct: `BLACK+DECKER BPACT08WT Portable Air Conditioner`,image: '',summary: ``,slug: ""},
			B07RMZV7W4: {href: "https://amzn.to/3eC9COE",nameProduct: `SereneLife SLPAC Portable Air Conditioner`,image: '',summary: ``,slug: ""},
			B08R6H7GVF: {href: "https://amzn.to/3eBk5Kd",nameProduct: `Hisense Portable Air Conditioner`,image: '',summary: ``,slug: ""},
			B08QRD11HN: {href: "https://amzn.to/3BltwHs",nameProduct: `Litheli 20V 13-Inch Cordless Brushless Lawn Mower`,image: '',summary: ``,slug: ""},
			B07N2XP5Z1: {href: "https://amzn.to/3BksVFP",nameProduct: `WORX WG384 40V Power Share Chainsaw`,image: '',summary: ``,slug: ""},
			B08YJTNNZT: {href: "https://amzn.to/3iua42z",nameProduct: `LawnMaster   Lawn Mower`,image: '',summary: ``,slug: ""},
			B01EJLBZSG: {href: "https://amzn.to/36OOnEU",nameProduct: `CMC-Classic Model Cars Mercedes-Benz W154 Seaman 16`,image: '',summary: ``,slug: ""},
			B07VR22832: {href: "https://amzn.to/3f3atrG",nameProduct: `Farberware Portable Dishwasher `,image: '',summary: ``,slug: ""},
			B086Z3J8ZC: {href: "https://amzn.to/3xeyWAx",nameProduct: `SAMSUNG Galaxy Tab S6 Lite`,image: '',summary: ``,slug: ""},
			B07HY8X46F: {href: "https://amzn.to/3zKgykV",nameProduct: `Windows 10 Tablet Windows 10 Fusion5`,image: '',summary: ``,slug: ""},
			B0192E2KCK: {href: "https://amzn.to/3rMxHaY",nameProduct: `Daron Skymarks Airbus House Colors A380-800 Airplane Model`,image: '',summary: ``,slug: ""},
			B07D9MRHP7: {href: "https://amzn.to/3l4XSZ9",nameProduct: `Whynter CDW- Energy Star Dishwasher`,image: '',summary: ``,slug: ""},
			B00VGGVQCI: {href: "https://amzn.to/3BRTbYA",nameProduct: `Breville Grind Control Coffee Maker`,image: '',summary: ``,slug: ""},
			B00YEYKNUK: {href: "https://amzn.to/3f5slSN",nameProduct: `OXO BREW Conical Burr Coffee Grinder`,image: '',summary: ``,slug: ""},
			B00YEYKK8U: {href: "https://amzn.to/3l3DQOq",nameProduct: `OXO Coffeemaker`,image: '',summary: ``,slug: ""},
			B00NGV49M0: {href: "https://amzn.to/2WzfvpP",nameProduct: `Ninja Nutri Blender`,image: '',summary: ``,slug: ""},
			B018SW6K7I: {href: "https://amzn.to/2VenUOz",nameProduct: `Panda PAN60SF 3.5 cu.ft Compact Portable Laundry Dryer`,image: '',summary: ``,slug: ""},
			B07PFVKXYD: {href: "https://amzn.to/3x5lXkF",nameProduct: `MIDEA 10,000 BTU EasyCool Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B08B4L4CGG: {href: "https://amzn.to/3lb8HZL",nameProduct: `COMFEE' Portable Washing Machine`,image: '',summary: ``,slug: ""},
			B08622KF4Z: {href: "https://amzn.to/3C0dLpM",nameProduct: `Panda PAN6360W Portable Washing Machine`,image: '',summary: ``,slug: ""},
			B0924JVC6C: {href: "https://amzn.to/2UZSjjZ",nameProduct: `New BiTECOOL CosBook Laptop`,image: '',summary: ``,slug: ""},
			B086Z3J8ZC: {href: "https://amzn.to/3ygZVgw",nameProduct: `SAMSUNG Galaxy Tab S6 Lite`,image: '',summary: ``,slug: ""},
			B08YKGZF7P: {href: "https://amzn.to/2UOse7v",nameProduct: `HP Chromebook 14 Laptop`,image: '',summary: ``,slug: ""},
			B006UKLUFS: {href: "https://amzn.to/2VfqaoX",nameProduct: `Cuisinart ICE-100 Compressor Ice Cream `,image: '',summary: ``,slug: ""},
			B00004RDF0: {href: "https://amzn.to/3l3eeRZ",nameProduct: `Lello 4080 Musso Lussino Ice Cream Maker`,image: '',summary: ``,slug: ""},
			B01FXMW4AS: {href: "https://amzn.to/3zLzcJ0",nameProduct: `Whynter ICM-201SB Upright Automatic Ice Cream Maker`,image: '',summary: ``,slug: ""},
			B08D96HXH7: {href: "https://amzn.to/3l2EOuj",nameProduct: `BODEGA 12 Volt Car Refrigerator`,image: '',summary: ``,slug: ""},
			B07P8QTFRC: {href: "https://amzn.to/3725svk",nameProduct: `DEWALT 12-Inch Miter Saw`,image: '',summary: ``,slug: ""},
			B083QZ5J2C: {href: "https://amzn.to/3BMMgzL",nameProduct: `COSTWAY Portable Car Refrigerator`,image: '',summary: ``,slug: ""},
			B07G3ZNK4Y: {href: "https://amzn.to/3xb0Xcu",nameProduct: `Vector Robot by Anki`,image: '',summary: ``,slug: ""},
			B06XT3F6Q8: {href: "https://amzn.to/3rMzpsU",nameProduct: `UBTECH Alpha 1 Pro Humanoid Robot`,image: '',summary: ``,slug: ""},
			B0762B4WHV: {href: "https://amzn.to/3BMxpp0",nameProduct: `Anki Cozmo`,image: '',summary: ``,slug: ""},
			B08QYJJS9B: {href: "https://amzn.to/3Au8Hby",nameProduct: `Coredy R580 Robot Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B000A7NN4I: {href: "https://amzn.to/2X8i8yS",nameProduct: `Zojirushi NS-ZCC18 Neuro Fuzzy Rice Cooker`,image: '',summary: ``,slug: ""},
			B001KBY9M8: {href: "https://amzn.to/3AnMr34",nameProduct: `Oster 6-Cup Rice Cooker with Steamer`,image: '',summary: ``,slug: ""},
			B00007J5U7: {href: "https://amzn.to/2VBD0hT",nameProduct: `Zojirushi Neuro Fuzzy Rice Cooker`,image: '',summary: ``,slug: ""},
			B07VGJMB9B: {href: "https://amzn.to/3sbiTCL",nameProduct: `Tesvor Robot Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B091FDX96H: {href: "https://amzn.to/3Aux09g",nameProduct: `TRIFO Robot Vacuum`,image: '',summary: ``,slug: ""},
			B08VKNVDDR: {href: "https://amzn.to/3CMIo2m",nameProduct: `Acer Aspire 5 Slim Laptop`,image: '',summary: ``,slug: ""},
			B086226DDB: {href: "https://amzn.to/3jDYOkK",nameProduct: `Lenovo Flex 5 14" Laptop`,image: '',summary: ``,slug: ""},
			B07R6P77HM: {href: "https://amzn.to/3fTOynj",nameProduct: `OEMTOOLS Commercial Fan`,image: '',summary: ``,slug: ""},
			B08221VG7G: {href: "https://amzn.to/3ArcFSa",nameProduct: `SINGER Intelligent 36T1 Steam Press`,image: '',summary: ``,slug: ""},
			B07D528W98: {href: "https://amzn.to/3AyeCMC",nameProduct: `YOSUDA Indoor Cycling Bike`,image: '',summary: ``,slug: ""},
			B07PMD1WG8: {href: "https://amzn.to/3fUc186",nameProduct: `Cyclace Exercise Bike`,image: '',summary: ``,slug: ""},
			B08JCLKHHW: {href: "https://amzn.to/3iBplzR",nameProduct: `RENPHO AI-Powered Exercise Bike`,image: '',summary: ``,slug: ""},
			B07S85TPLG: {href: "https://amzn.to/3AyeZH0",nameProduct: `Ninja FD401 Deluxe Pressure Cooker`,image: '',summary: ``,slug: ""},
			B07V9PC6XT: {href: "https://amzn.to/3lSFjri",nameProduct: `Brother ST150HDH Sewing Machine`,image: '',summary: ``,slug: ""},
			B01J4HIY2K: {href: "https://amzn.to/3CCehKR",nameProduct: `Janome Sewing Machine`,image: '',summary: ``,slug: ""},
			B019BYTIGW: {href: "https://amzn.to/3lRBdQd",nameProduct: `AZOOU Race Timing Clock Timer`,image: '',summary: ``,slug: ""},
			B08P48MZFS: {href: "https://amzn.to/3jCeh4E",nameProduct: `Bose Soundlink Mini II Special Edition`,image: '',summary: ``,slug: ""},
			B08P48MZFS: {href: "https://amzn.to/3jCeh4E",nameProduct: `Bose Soundlink Mini II Special Edition`,image: '',summary: ``,slug: ""},
			B094T6NYV9: {href: "https://amzn.to/2VMeRoL",nameProduct: `Sony SRS-XG500 X-Series Bluetooth Speaker`,image: '',summary: ``,slug: ""},
			B07N76WN9Z: {href: "https://amzn.to/3jLDPfQ",nameProduct: `Generac 7676 GP8000E Portable Generator`,image: '',summary: ``,slug: ""},
			B08DP2BQ7T: {href: "https://amzn.to/3yD43HR",nameProduct: `1:14 Remote Control Full Metal Bulldozer Toy`,image: '',summary: ``,slug: ""},
			B0923CMNS5: {href: "https://amzn.to/2XlBP6J",nameProduct: `HUINA 1580 V4 Excavator RC`,image: '',summary: ``,slug: ""},
			B08HR68MQZ: {href: "https://amzn.to/3jMFiT0",nameProduct: `Corsair K100 RGB Mechanical Gaming Keyboard `,image: '',summary: ``,slug: ""},
			B096SBSTFL: {href: "https://amzn.to/3oGQRze",nameProduct: `Bose QuietComfort Wireless Earphones`,image: '',summary: ``,slug: ""},
			B01N9K9N33: {href: "https://amzn.to/3DkreZj",nameProduct: `Thrustmaster TMX PRO Racing Wheel`,image: '',summary: ``,slug: ""},
			B01D3FOCVQ: {href: "https://amzn.to/3Bolq0d",nameProduct: `LG LW1216HR Window-Mounted Air Conditioner`,image: '',summary: ``,slug: ""},
			B087N4LQPN: {href: "https://amzn.to/3DjfdTR",nameProduct: `Alienware 240Hz Gaming Monitor`,image: '',summary: ``,slug: ""},
			B08FBK2DK5: {href: "https://amzn.to/3FmiQdL",nameProduct: `CyberpowerPC Gamer Xtreme VR Gaming PC`,image: '',summary: ``,slug: ""},
			B08BF4CZSV: {href: "https://amzn.to/3oLqE2L",nameProduct: `HP 24mh FHD Monitor - Computer Monitor`,image: '',summary: ``,slug: ""},
			B074JDN6P4: {href: "https://amzn.to/2YDXBDz",nameProduct: `Toyota Sprinter Trueno AE86 1/18 Model Car `,image: '',summary: ``,slug: ""},
			B07XKWCKCY: {href: "https://amzn.to/3Ar8KEI",nameProduct: `Smeg KLF03GOUS Electric Kettle`,image: '',summary: ``,slug: ""},
			B07QM2H5TR: {href: "https://amzn.to/3BIfdN3",nameProduct: `Comfort Zone CZ230ER Heaters`,image: '',summary: ``,slug: ""},
			B00C1WRG7K: {href: "https://amzn.to/3FAiJeH",nameProduct: `Ultra Grind+ Gold Wet Grinder`,image: '',summary: ``,slug: ""},
			B07BLZX73S: {href: "https://amzn.to/2YAxBZc",nameProduct: `Bose S1 Pro Portable Bluetooth Speaker `,image: '',summary: ``,slug: ""},
			B07F39ZKK9: {href: "https://amzn.to/2Yygxnm",nameProduct: `Bose Surround Speakers`,image: '',summary: ``,slug: ""},
			B097PG8TYZ: {href: "https://amzn.to/3FyiuRe",nameProduct: `MOONCOOL Mountain Bikes`,image: '',summary: ``,slug: ""},
			B07D528W98: {href: "https://amzn.to/3oTx7ZD",nameProduct: `YOSUDA Indoor Cycling Bike`,image: '',summary: ``,slug: ""},
			B07PMD1WG8: {href: "https://amzn.to/3DtJqQ6",nameProduct: `Cyclace Exercise Bike Stationary`,image: '',summary: ``,slug: ""},
			B07NQKSK64: {href: "https://amzn.to/3mCeGWl",nameProduct: `Panasonic ER-GP82 Hair Clipper`,image: '',summary: ``,slug: ""},
			B08156NWQ2: {href: "https://amzn.to/3mCePcA",nameProduct: `Andis 12470 Blade Hair Clipper`,image: '',summary: ``,slug: ""},
			B07D2M1SGB: {href: "https://amzn.to/3oODj52",nameProduct: `Andis 79005 Supra ZR II Blade Clipper `,image: '',summary: ``,slug: ""},
			B099PWQZ8R: {href: "https://amzn.to/3Dt5Q4c",nameProduct: `ASUS ROG Strix G17 Gaming Laptop`,image: '',summary: ``,slug: ""},
			B08N5M7S6K: {href: "https://amzn.to/3FB3qSG",nameProduct: `Apple MacBook Air Laptop`,image: '',summary: ``,slug: ""},
			B07DV4T9ND: {href: "https://amzn.to/3j1KW4i",nameProduct: `NESCAFÉ Dolce Gusto Coffee Machine`,image: '',summary: ``,slug: ""},
			B08XMB3SGW: {href: "https://amzn.to/3aDsGty",nameProduct: `Fire HD 10 Plus tablet`,image: '',summary: ``,slug: ""},
			B07KYN589K: {href: "https://amzn.to/3BM1QeA",nameProduct: `Google Nest Learning Thermostat`,image: '',summary: ``,slug: ""},
			B08W74J4CH: {href: "https://amzn.to/2YNY0DE",nameProduct: `All-new Ring Video Doorbell 4`,image: '',summary: ``,slug: ""},
			B087792CQT: {href: "https://amzn.to/3FWr8cD",nameProduct: `ViewSonic 15.6 Inch 1080p Portable Monitor`,image: '',summary: ``,slug: ""},
			B07NSSWPC5: {href: "https://amzn.to/3AMKNba",nameProduct: `ASTRO Gaming A40 TR Wired Headset`,image: '',summary: ``,slug: ""},
			B08746M1NX: {href: "https://amzn.to/3p5L7zk",nameProduct: `Waterdrop RO Osmosis Water Filtration`,image: '',summary: ``,slug: ""},
			B08GZKZF87: {href: "https://amzn.to/3ARX7qF",nameProduct: `Microsoft Surface Laptop Go`,image: '',summary: ``,slug: ""},
			B0725K9WQG: {href: "https://amzn.to/2YPSJuD",nameProduct: `EGO Power+ CS1604 Cordless Chainsaw `,image: '',summary: ``,slug: ""},
			B0863TXGM3: {href: "https://amzn.to/3p1xbWZ",nameProduct: `Sony WH-1000XM4 Wireless Headphones`,image: '',summary: ``,slug: ""},
			B08GW982QS: {href: "https://amzn.to/3ALnaPT",nameProduct: `TCL 65-inch 4K UHD HDR Smart Roku TV`,image: '',summary: ``,slug: ""},
			B09BZ9KXY3: {href: "https://amzn.to/3mWL9qH",nameProduct: `Byootique 4 in1 Makeup Case Cosmetic Box`,image: '',summary: ``,slug: ""},
			B01ALBMIEI: {href: "https://amzn.to/3lCX8dA",nameProduct: `Giantex Portable Mini Washing Machine`,image: '',summary: ``,slug: ""},
			B004UJKKI4: {href: "https://amzn.to/3p3RdAi",nameProduct: `Waring Commercial MX1200XTX 3.5 HP Blender`,image: '',summary: ``,slug: ""},
			B093DY2WY4: {href: "https://amzn.to/3vjDir2",nameProduct: `Moccamaster 53935 KBGV Coffee Maker`,image: '',summary: ``,slug: ""},
			B08L41KGBH: {href: "https://amzn.to/2Z0juxe",nameProduct: `Apple Watch Series 6`,image: '',summary: ``,slug: ""},
			B01DTYAZO4: {href: "https://amzn.to/3DTOYUp",nameProduct: `BISSELL Crosswave Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07QNM91NQ: {href: "https://amzn.to/3aMZ114",nameProduct: `iRobot Braava Jet M6 Robot Mop`,image: '',summary: ``,slug: ""},
			B082LZKYFL: {href: "https://amzn.to/3lRIbUW",nameProduct: `NETGEAR Orbi Wifi 6 System`,image: '',summary: ``,slug: ""},
			B091ZHW35L: {href: "https://amzn.to/30vuG56",nameProduct: `Cuisinart SS-15W 12-Cup Coffeemaker`,image: '',summary: ``,slug: ""},
			B091GGZT1S: {href: "https://amzn.to/2ZbXKhE",nameProduct: `MSI Stealth 15M Gaming Laptop`,image: '',summary: ``,slug: ""},
			B07QQ7PHJJ: {href: "https://amzn.to/3DODwcy",nameProduct: `Bose Surround Speakers 700`,image: '',summary: ``,slug: ""},
			B01DQ19B1S: {href: "https://amzn.to/3lS5HRD",nameProduct: `DEWALT 20V MAX XR Cordless Drill`,image: '',summary: ``,slug: ""},
			B0846NH2PS: {href: "https://amzn.to/3DTsGSO",nameProduct: `Sony X950H 65-inch TV`,image: '',summary: ``,slug: ""},
			B08YKG5K7F: {href: "https://amzn.to/3AWbfz5",nameProduct: `Lenovo Legion 5 15 Gaming Laptop`,image: '',summary: ``,slug: ""},
			B0873LVX4P: {href: "https://amzn.to/3aQnPFj",nameProduct: `Bang & Olufsen Beoplay E8 Earphones`,image: '',summary: ``,slug: ""},
			B07X43B6FD: {href: "https://amzn.to/3pdAo5V",nameProduct: `Sony Alpha A6600 Mirrorless Camera`,image: '',summary: ``,slug: ""},
			B07GSH7FGX: {href: "https://amzn.to/3jfhSGN",nameProduct: `Cricut Maker`,image: '',summary: ``,slug: ""},
			B08L3X9ZZX: {href: "https://amzn.to/2Z57jys",nameProduct: `Ubiquiti UniFi Protect G4 Doorbell`,image: '',summary: ``,slug: ""},
			B09973TGP9: {href: "https://amzn.to/3BYoccR",nameProduct: `Samsung Galaxy Tab S7 FE`,image: '',summary: ``,slug: ""},
			B08BP59X75: {href: "https://amzn.to/3E4sNe5",nameProduct: `Segway Ninebot E22 E45 Electric Kick Scooter`,image: '',summary: ``,slug: ""},
			B07DVY8H3F: {href: "https://amzn.to/30RkrIF",nameProduct: `Pado Ozen 500 Vacuum Blender`,image: '',summary: ``,slug: ""},
			B0874XJYW8: {href: "https://amzn.to/3CbmUeI",nameProduct: `Toshiba 43LF621U21 43-inch Smart`,image: '',summary: ``,slug: ""},
			B00M4LWXI0: {href: "https://amzn.to/3E3fHOo",nameProduct: `Apple iMac`,image: '',summary: ``,slug: ""},
			B08Z3DYBMC: {href: "https://amzn.to/30VGNsF",nameProduct: `DJI Air 2S - Drone Quadcopter UAV`,image: '',summary: ``,slug: ""},
			B07TC72FP6: {href: "https://amzn.to/3DXjmxc",nameProduct: `Champion 100402 2000-Watt Portable Generator`,image: '',summary: ``,slug: ""},
			B09FTJYV1X: {href: "https://amzn.to/3E9xDXs",nameProduct: `Snow Joe 24V-X2 iON+Snow Blower Kit`,image: '',summary: ``,slug: ""},
			B085Z35GY6: {href: "https://amzn.to/3psxjiD",nameProduct: `TP-Link Deco WiFi 6 Mesh System`,image: '',summary: ``,slug: ""},
			B07P97JJNZ: {href: "https://amzn.to/3AZWNpK",nameProduct: `Miele Classic C1 Canister Vacuum`,image: '',summary: ``,slug: ""},
			B0976YH2QF: {href: "https://amzn.to/3ngtjz3",nameProduct: `VIOMI Robot Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B0756GB78C: {href: "https://amzn.to/3m4t5vt",nameProduct: `Bose QuietComfort 35 II Bluetooth Headphones`,image: '',summary: ``,slug: ""},
			B01M0AGJIQ: {href: "https://amzn.to/3aZKBe7",nameProduct: `Duraflame Infrared Electric Fireplace Stove`,image: '',summary: ``,slug: ""},
			B08ZYYC9G4: {href: "https://amzn.to/30SACFC",nameProduct: `ASUS ZenBook 14 Ultra-Slim Laptop`,image: '',summary: ``,slug: ""},
			B07H7CZ6BZ: {href: "https://amzn.to/3aZKT4H",nameProduct: `Marshall Kilburn II Bluetooth Speaker`,image: '',summary: ``,slug: ""},
			B085RFFC9Q: {href: "https://amzn.to/3C5EGjq",nameProduct: `Logitech G915 TKL Tenkeyless Wireless Keyboard`,image: '',summary: ``,slug: ""}
		}
	}
	return dataAMZ;
}
